# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

"""
Python interface to Automtion Proxy.
"""

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyautolib', [dirname(__file__)])
        except ImportError:
            import _pyautolib
            return _pyautolib
        if fp is not None:
            try:
                _mod = imp.load_module('_pyautolib', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pyautolib = swig_import_helper()
    del swig_import_helper
else:
    import _pyautolib
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


IDC_MinimumLabelValue = _pyautolib.IDC_MinimumLabelValue
IDC_Messages = _pyautolib.IDC_Messages
IDC_MessagesAll = _pyautolib.IDC_MessagesAll
IDC_MessagesNone = _pyautolib.IDC_MessagesNone
IDC_BACK = _pyautolib.IDC_BACK
IDC_FORWARD = _pyautolib.IDC_FORWARD
IDC_RELOAD = _pyautolib.IDC_RELOAD
IDC_HOME = _pyautolib.IDC_HOME
IDC_OPEN_CURRENT_URL = _pyautolib.IDC_OPEN_CURRENT_URL
IDC_STOP = _pyautolib.IDC_STOP
IDC_RELOAD_IGNORING_CACHE = _pyautolib.IDC_RELOAD_IGNORING_CACHE
IDC_NEW_WINDOW = _pyautolib.IDC_NEW_WINDOW
IDC_NEW_INCOGNITO_WINDOW = _pyautolib.IDC_NEW_INCOGNITO_WINDOW
IDC_CLOSE_WINDOW = _pyautolib.IDC_CLOSE_WINDOW
IDC_ALWAYS_ON_TOP = _pyautolib.IDC_ALWAYS_ON_TOP
IDC_NEW_TAB = _pyautolib.IDC_NEW_TAB
IDC_CLOSE_TAB = _pyautolib.IDC_CLOSE_TAB
IDC_SELECT_NEXT_TAB = _pyautolib.IDC_SELECT_NEXT_TAB
IDC_SELECT_PREVIOUS_TAB = _pyautolib.IDC_SELECT_PREVIOUS_TAB
IDC_SELECT_TAB_0 = _pyautolib.IDC_SELECT_TAB_0
IDC_SELECT_TAB_1 = _pyautolib.IDC_SELECT_TAB_1
IDC_SELECT_TAB_2 = _pyautolib.IDC_SELECT_TAB_2
IDC_SELECT_TAB_3 = _pyautolib.IDC_SELECT_TAB_3
IDC_SELECT_TAB_4 = _pyautolib.IDC_SELECT_TAB_4
IDC_SELECT_TAB_5 = _pyautolib.IDC_SELECT_TAB_5
IDC_SELECT_TAB_6 = _pyautolib.IDC_SELECT_TAB_6
IDC_SELECT_TAB_7 = _pyautolib.IDC_SELECT_TAB_7
IDC_SELECT_LAST_TAB = _pyautolib.IDC_SELECT_LAST_TAB
IDC_DUPLICATE_TAB = _pyautolib.IDC_DUPLICATE_TAB
IDC_RESTORE_TAB = _pyautolib.IDC_RESTORE_TAB
IDC_SHOW_AS_TAB = _pyautolib.IDC_SHOW_AS_TAB
IDC_FULLSCREEN = _pyautolib.IDC_FULLSCREEN
IDC_EXIT = _pyautolib.IDC_EXIT
IDC_MOVE_TAB_NEXT = _pyautolib.IDC_MOVE_TAB_NEXT
IDC_MOVE_TAB_PREVIOUS = _pyautolib.IDC_MOVE_TAB_PREVIOUS
IDC_TOGGLE_VERTICAL_TABS = _pyautolib.IDC_TOGGLE_VERTICAL_TABS
IDC_SEARCH = _pyautolib.IDC_SEARCH
IDC_TABPOSE = _pyautolib.IDC_TABPOSE
IDC_COMPACT_NAVBAR = _pyautolib.IDC_COMPACT_NAVBAR
IDC_DEBUG_FRAME_TOGGLE = _pyautolib.IDC_DEBUG_FRAME_TOGGLE
IDC_BOOKMARK_PAGE = _pyautolib.IDC_BOOKMARK_PAGE
IDC_BOOKMARK_ALL_TABS = _pyautolib.IDC_BOOKMARK_ALL_TABS
IDC_VIEW_SOURCE = _pyautolib.IDC_VIEW_SOURCE
IDC_PRINT = _pyautolib.IDC_PRINT
IDC_SAVE_PAGE = _pyautolib.IDC_SAVE_PAGE
IDC_ENCODING_MENU = _pyautolib.IDC_ENCODING_MENU
IDC_EMAIL_PAGE_LOCATION = _pyautolib.IDC_EMAIL_PAGE_LOCATION
IDC_ENCODING_AUTO_DETECT = _pyautolib.IDC_ENCODING_AUTO_DETECT
IDC_ENCODING_UTF8 = _pyautolib.IDC_ENCODING_UTF8
IDC_ENCODING_UTF16LE = _pyautolib.IDC_ENCODING_UTF16LE
IDC_ENCODING_ISO88591 = _pyautolib.IDC_ENCODING_ISO88591
IDC_ENCODING_WINDOWS1252 = _pyautolib.IDC_ENCODING_WINDOWS1252
IDC_ENCODING_GBK = _pyautolib.IDC_ENCODING_GBK
IDC_ENCODING_GB18030 = _pyautolib.IDC_ENCODING_GB18030
IDC_ENCODING_BIG5 = _pyautolib.IDC_ENCODING_BIG5
IDC_ENCODING_BIG5HKSCS = _pyautolib.IDC_ENCODING_BIG5HKSCS
IDC_ENCODING_KOREAN = _pyautolib.IDC_ENCODING_KOREAN
IDC_ENCODING_SHIFTJIS = _pyautolib.IDC_ENCODING_SHIFTJIS
IDC_ENCODING_ISO2022JP = _pyautolib.IDC_ENCODING_ISO2022JP
IDC_ENCODING_EUCJP = _pyautolib.IDC_ENCODING_EUCJP
IDC_ENCODING_THAI = _pyautolib.IDC_ENCODING_THAI
IDC_ENCODING_ISO885915 = _pyautolib.IDC_ENCODING_ISO885915
IDC_ENCODING_MACINTOSH = _pyautolib.IDC_ENCODING_MACINTOSH
IDC_ENCODING_ISO88592 = _pyautolib.IDC_ENCODING_ISO88592
IDC_ENCODING_WINDOWS1250 = _pyautolib.IDC_ENCODING_WINDOWS1250
IDC_ENCODING_ISO88595 = _pyautolib.IDC_ENCODING_ISO88595
IDC_ENCODING_WINDOWS1251 = _pyautolib.IDC_ENCODING_WINDOWS1251
IDC_ENCODING_KOI8R = _pyautolib.IDC_ENCODING_KOI8R
IDC_ENCODING_KOI8U = _pyautolib.IDC_ENCODING_KOI8U
IDC_ENCODING_ISO88597 = _pyautolib.IDC_ENCODING_ISO88597
IDC_ENCODING_WINDOWS1253 = _pyautolib.IDC_ENCODING_WINDOWS1253
IDC_ENCODING_ISO88594 = _pyautolib.IDC_ENCODING_ISO88594
IDC_ENCODING_ISO885913 = _pyautolib.IDC_ENCODING_ISO885913
IDC_ENCODING_WINDOWS1257 = _pyautolib.IDC_ENCODING_WINDOWS1257
IDC_ENCODING_ISO88593 = _pyautolib.IDC_ENCODING_ISO88593
IDC_ENCODING_ISO885910 = _pyautolib.IDC_ENCODING_ISO885910
IDC_ENCODING_ISO885914 = _pyautolib.IDC_ENCODING_ISO885914
IDC_ENCODING_ISO885916 = _pyautolib.IDC_ENCODING_ISO885916
IDC_ENCODING_WINDOWS1254 = _pyautolib.IDC_ENCODING_WINDOWS1254
IDC_ENCODING_ISO88596 = _pyautolib.IDC_ENCODING_ISO88596
IDC_ENCODING_WINDOWS1256 = _pyautolib.IDC_ENCODING_WINDOWS1256
IDC_ENCODING_ISO88598 = _pyautolib.IDC_ENCODING_ISO88598
IDC_ENCODING_WINDOWS1255 = _pyautolib.IDC_ENCODING_WINDOWS1255
IDC_ENCODING_WINDOWS1258 = _pyautolib.IDC_ENCODING_WINDOWS1258
IDC_ENCODING_ISO88598I = _pyautolib.IDC_ENCODING_ISO88598I
IDC_CUT = _pyautolib.IDC_CUT
IDC_COPY = _pyautolib.IDC_COPY
IDC_COPY_URL = _pyautolib.IDC_COPY_URL
IDC_PASTE = _pyautolib.IDC_PASTE
IDC_EDIT_MENU = _pyautolib.IDC_EDIT_MENU
IDC_FIND = _pyautolib.IDC_FIND
IDC_FIND_NEXT = _pyautolib.IDC_FIND_NEXT
IDC_FIND_PREVIOUS = _pyautolib.IDC_FIND_PREVIOUS
IDC_ZOOM_MENU = _pyautolib.IDC_ZOOM_MENU
IDC_ZOOM_PLUS = _pyautolib.IDC_ZOOM_PLUS
IDC_ZOOM_NORMAL = _pyautolib.IDC_ZOOM_NORMAL
IDC_ZOOM_MINUS = _pyautolib.IDC_ZOOM_MINUS
IDC_ZOOM_PERCENT_DISPLAY = _pyautolib.IDC_ZOOM_PERCENT_DISPLAY
IDC_FOCUS_TOOLBAR = _pyautolib.IDC_FOCUS_TOOLBAR
IDC_FOCUS_LOCATION = _pyautolib.IDC_FOCUS_LOCATION
IDC_FOCUS_SEARCH = _pyautolib.IDC_FOCUS_SEARCH
IDC_FOCUS_MENU_BAR = _pyautolib.IDC_FOCUS_MENU_BAR
IDC_FOCUS_NEXT_PANE = _pyautolib.IDC_FOCUS_NEXT_PANE
IDC_FOCUS_PREVIOUS_PANE = _pyautolib.IDC_FOCUS_PREVIOUS_PANE
IDC_FOCUS_BOOKMARKS = _pyautolib.IDC_FOCUS_BOOKMARKS
IDC_FOCUS_CHROMEOS_STATUS = _pyautolib.IDC_FOCUS_CHROMEOS_STATUS
IDC_OPEN_FILE = _pyautolib.IDC_OPEN_FILE
IDC_CREATE_SHORTCUTS = _pyautolib.IDC_CREATE_SHORTCUTS
IDC_DEVELOPER_MENU = _pyautolib.IDC_DEVELOPER_MENU
IDC_DEV_TOOLS = _pyautolib.IDC_DEV_TOOLS
IDC_DEV_TOOLS_CONSOLE = _pyautolib.IDC_DEV_TOOLS_CONSOLE
IDC_TASK_MANAGER = _pyautolib.IDC_TASK_MANAGER
IDC_FEEDBACK = _pyautolib.IDC_FEEDBACK
IDC_SHOW_BOOKMARK_BAR = _pyautolib.IDC_SHOW_BOOKMARK_BAR
IDC_SHOW_HISTORY = _pyautolib.IDC_SHOW_HISTORY
IDC_SHOW_BOOKMARK_MANAGER = _pyautolib.IDC_SHOW_BOOKMARK_MANAGER
IDC_SHOW_DOWNLOADS = _pyautolib.IDC_SHOW_DOWNLOADS
IDC_CLEAR_BROWSING_DATA = _pyautolib.IDC_CLEAR_BROWSING_DATA
IDC_IMPORT_SETTINGS = _pyautolib.IDC_IMPORT_SETTINGS
IDC_OPTIONS = _pyautolib.IDC_OPTIONS
IDC_EDIT_SEARCH_ENGINES = _pyautolib.IDC_EDIT_SEARCH_ENGINES
IDC_VIEW_PASSWORDS = _pyautolib.IDC_VIEW_PASSWORDS
IDC_ABOUT = _pyautolib.IDC_ABOUT
IDC_HELP_PAGE = _pyautolib.IDC_HELP_PAGE
IDC_SHOW_APP_MENU = _pyautolib.IDC_SHOW_APP_MENU
IDC_MANAGE_EXTENSIONS = _pyautolib.IDC_MANAGE_EXTENSIONS
IDC_AUTOFILL_DEFAULT = _pyautolib.IDC_AUTOFILL_DEFAULT
IDC_DEV_TOOLS_INSPECT = _pyautolib.IDC_DEV_TOOLS_INSPECT
IDC_UPGRADE_DIALOG = _pyautolib.IDC_UPGRADE_DIALOG
IDC_VIEW_INCOMPATIBILITIES = _pyautolib.IDC_VIEW_INCOMPATIBILITIES
IDC_VIEW_BACKGROUND_PAGES = _pyautolib.IDC_VIEW_BACKGROUND_PAGES
IDC_SHOW_KEYBOARD_OVERLAY = _pyautolib.IDC_SHOW_KEYBOARD_OVERLAY
IDC_PROFILING_ENABLED = _pyautolib.IDC_PROFILING_ENABLED
IDC_FILE_MANAGER = _pyautolib.IDC_FILE_MANAGER
IDC_BOOKMARKS_MENU = _pyautolib.IDC_BOOKMARKS_MENU
IDC_PROFILE_MENU = _pyautolib.IDC_PROFILE_MENU
IDC_CREATE_NEW_PROFILE = _pyautolib.IDC_CREATE_NEW_PROFILE
IDC_SPELLCHECK_SUGGESTION_0 = _pyautolib.IDC_SPELLCHECK_SUGGESTION_0
IDC_SPELLCHECK_SUGGESTION_1 = _pyautolib.IDC_SPELLCHECK_SUGGESTION_1
IDC_SPELLCHECK_SUGGESTION_2 = _pyautolib.IDC_SPELLCHECK_SUGGESTION_2
IDC_SPELLCHECK_SUGGESTION_3 = _pyautolib.IDC_SPELLCHECK_SUGGESTION_3
IDC_SPELLCHECK_SUGGESTION_4 = _pyautolib.IDC_SPELLCHECK_SUGGESTION_4
IDC_SPELLCHECK_SUGGESTION_LAST = _pyautolib.IDC_SPELLCHECK_SUGGESTION_LAST
IDC_SPELLCHECK_MENU = _pyautolib.IDC_SPELLCHECK_MENU
IDC_SPELLCHECK_LANGUAGES_FIRST = _pyautolib.IDC_SPELLCHECK_LANGUAGES_FIRST
IDC_SPELLCHECK_LANGUAGES_LAST = _pyautolib.IDC_SPELLCHECK_LANGUAGES_LAST
IDC_CHECK_SPELLING_OF_THIS_FIELD = _pyautolib.IDC_CHECK_SPELLING_OF_THIS_FIELD
IDC_SYNC_BOOKMARKS = _pyautolib.IDC_SYNC_BOOKMARKS
IDC_SPELLPANEL_TOGGLE = _pyautolib.IDC_SPELLPANEL_TOGGLE
IDC_SPELLCHECK_ADD_TO_DICTIONARY = _pyautolib.IDC_SPELLCHECK_ADD_TO_DICTIONARY
IDC_WRITING_DIRECTION_MENU = _pyautolib.IDC_WRITING_DIRECTION_MENU
IDC_WRITING_DIRECTION_DEFAULT = _pyautolib.IDC_WRITING_DIRECTION_DEFAULT
IDC_WRITING_DIRECTION_LTR = _pyautolib.IDC_WRITING_DIRECTION_LTR
IDC_WRITING_DIRECTION_RTL = _pyautolib.IDC_WRITING_DIRECTION_RTL
IDC_TRANSLATE_OPTIONS_ALWAYS = _pyautolib.IDC_TRANSLATE_OPTIONS_ALWAYS
IDC_TRANSLATE_OPTIONS_NEVER_TRANSLATE_LANG = _pyautolib.IDC_TRANSLATE_OPTIONS_NEVER_TRANSLATE_LANG
IDC_TRANSLATE_OPTIONS_NEVER_TRANSLATE_SITE = _pyautolib.IDC_TRANSLATE_OPTIONS_NEVER_TRANSLATE_SITE
IDC_TRANSLATE_REPORT_BAD_LANGUAGE_DETECTION = _pyautolib.IDC_TRANSLATE_REPORT_BAD_LANGUAGE_DETECTION
IDC_TRANSLATE_OPTIONS_ABOUT = _pyautolib.IDC_TRANSLATE_OPTIONS_ABOUT
IDC_TRANSLATE_ORIGINAL_LANGUAGE_BASE = _pyautolib.IDC_TRANSLATE_ORIGINAL_LANGUAGE_BASE
IDC_TRANSLATE_TARGET_LANGUAGE_BASE = _pyautolib.IDC_TRANSLATE_TARGET_LANGUAGE_BASE
IDC_VIEW_MENU = _pyautolib.IDC_VIEW_MENU
IDC_SYSTEM_OPTIONS = _pyautolib.IDC_SYSTEM_OPTIONS
IDC_INTERNET_OPTIONS = _pyautolib.IDC_INTERNET_OPTIONS
IDC_LANGUAGE_OPTIONS = _pyautolib.IDC_LANGUAGE_OPTIONS
IDC_HISTORY_MENU = _pyautolib.IDC_HISTORY_MENU
IDC_INPUT_METHODS_MENU = _pyautolib.IDC_INPUT_METHODS_MENU
IDC_CONTENT_CONTEXT_CUSTOM_FIRST = _pyautolib.IDC_CONTENT_CONTEXT_CUSTOM_FIRST
IDC_CONTENT_CONTEXT_CUSTOM_LAST = _pyautolib.IDC_CONTENT_CONTEXT_CUSTOM_LAST
IDC_EXTENSIONS_CONTEXT_CUSTOM_FIRST = _pyautolib.IDC_EXTENSIONS_CONTEXT_CUSTOM_FIRST
IDC_EXTENSIONS_CONTEXT_CUSTOM_LAST = _pyautolib.IDC_EXTENSIONS_CONTEXT_CUSTOM_LAST
IDC_CONTENT_CONTEXT_OPENLINKNEWTAB = _pyautolib.IDC_CONTENT_CONTEXT_OPENLINKNEWTAB
IDC_CONTENT_CONTEXT_OPENLINKNEWWINDOW = _pyautolib.IDC_CONTENT_CONTEXT_OPENLINKNEWWINDOW
IDC_CONTENT_CONTEXT_OPENLINKOFFTHERECORD = _pyautolib.IDC_CONTENT_CONTEXT_OPENLINKOFFTHERECORD
IDC_CONTENT_CONTEXT_SAVELINKAS = _pyautolib.IDC_CONTENT_CONTEXT_SAVELINKAS
IDC_CONTENT_CONTEXT_COPYLINKLOCATION = _pyautolib.IDC_CONTENT_CONTEXT_COPYLINKLOCATION
IDC_CONTENT_CONTEXT_COPYEMAILADDRESS = _pyautolib.IDC_CONTENT_CONTEXT_COPYEMAILADDRESS
IDC_CONTENT_CONTEXT_SAVEIMAGEAS = _pyautolib.IDC_CONTENT_CONTEXT_SAVEIMAGEAS
IDC_CONTENT_CONTEXT_COPYIMAGELOCATION = _pyautolib.IDC_CONTENT_CONTEXT_COPYIMAGELOCATION
IDC_CONTENT_CONTEXT_COPYIMAGE = _pyautolib.IDC_CONTENT_CONTEXT_COPYIMAGE
IDC_CONTENT_CONTEXT_OPENIMAGENEWTAB = _pyautolib.IDC_CONTENT_CONTEXT_OPENIMAGENEWTAB
IDC_CONTENT_CONTEXT_SAVEAVAS = _pyautolib.IDC_CONTENT_CONTEXT_SAVEAVAS
IDC_CONTENT_CONTEXT_COPYAVLOCATION = _pyautolib.IDC_CONTENT_CONTEXT_COPYAVLOCATION
IDC_CONTENT_CONTEXT_OPENAVNEWTAB = _pyautolib.IDC_CONTENT_CONTEXT_OPENAVNEWTAB
IDC_CONTENT_CONTEXT_PLAYPAUSE = _pyautolib.IDC_CONTENT_CONTEXT_PLAYPAUSE
IDC_CONTENT_CONTEXT_MUTE = _pyautolib.IDC_CONTENT_CONTEXT_MUTE
IDC_CONTENT_CONTEXT_LOOP = _pyautolib.IDC_CONTENT_CONTEXT_LOOP
IDC_CONTENT_CONTEXT_CONTROLS = _pyautolib.IDC_CONTENT_CONTEXT_CONTROLS
IDC_CONTENT_CONTEXT_COPY = _pyautolib.IDC_CONTENT_CONTEXT_COPY
IDC_CONTENT_CONTEXT_CUT = _pyautolib.IDC_CONTENT_CONTEXT_CUT
IDC_CONTENT_CONTEXT_PASTE = _pyautolib.IDC_CONTENT_CONTEXT_PASTE
IDC_CONTENT_CONTEXT_DELETE = _pyautolib.IDC_CONTENT_CONTEXT_DELETE
IDC_CONTENT_CONTEXT_UNDO = _pyautolib.IDC_CONTENT_CONTEXT_UNDO
IDC_CONTENT_CONTEXT_REDO = _pyautolib.IDC_CONTENT_CONTEXT_REDO
IDC_CONTENT_CONTEXT_SELECTALL = _pyautolib.IDC_CONTENT_CONTEXT_SELECTALL
IDC_CONTENT_CONTEXT_TRANSLATE = _pyautolib.IDC_CONTENT_CONTEXT_TRANSLATE
IDC_CONTENT_CONTEXT_INSPECTELEMENT = _pyautolib.IDC_CONTENT_CONTEXT_INSPECTELEMENT
IDC_CONTENT_CONTEXT_VIEWPAGEINFO = _pyautolib.IDC_CONTENT_CONTEXT_VIEWPAGEINFO
IDC_CONTENT_CONTEXT_LANGUAGE_SETTINGS = _pyautolib.IDC_CONTENT_CONTEXT_LANGUAGE_SETTINGS
IDC_CONTENT_CONTEXT_LOOK_UP_IN_DICTIONARY = _pyautolib.IDC_CONTENT_CONTEXT_LOOK_UP_IN_DICTIONARY
IDC_CONTENT_CONTEXT_RELOADFRAME = _pyautolib.IDC_CONTENT_CONTEXT_RELOADFRAME
IDC_CONTENT_CONTEXT_VIEWFRAMESOURCE = _pyautolib.IDC_CONTENT_CONTEXT_VIEWFRAMESOURCE
IDC_CONTENT_CONTEXT_VIEWFRAMEINFO = _pyautolib.IDC_CONTENT_CONTEXT_VIEWFRAMEINFO
IDC_CONTENT_CONTEXT_GOTOURL = _pyautolib.IDC_CONTENT_CONTEXT_GOTOURL
IDC_CONTENT_CONTEXT_SEARCHWEBFOR = _pyautolib.IDC_CONTENT_CONTEXT_SEARCHWEBFOR
IDC_BOOKMARK_BAR_OPEN_ALL = _pyautolib.IDC_BOOKMARK_BAR_OPEN_ALL
IDC_BOOKMARK_BAR_OPEN_ALL_NEW_WINDOW = _pyautolib.IDC_BOOKMARK_BAR_OPEN_ALL_NEW_WINDOW
IDC_BOOKMARK_BAR_OPEN_ALL_INCOGNITO = _pyautolib.IDC_BOOKMARK_BAR_OPEN_ALL_INCOGNITO
IDC_BOOKMARK_BAR_OPEN_INCOGNITO = _pyautolib.IDC_BOOKMARK_BAR_OPEN_INCOGNITO
IDC_BOOKMARK_BAR_RENAME_FOLDER = _pyautolib.IDC_BOOKMARK_BAR_RENAME_FOLDER
IDC_BOOKMARK_BAR_EDIT = _pyautolib.IDC_BOOKMARK_BAR_EDIT
IDC_BOOKMARK_BAR_REMOVE = _pyautolib.IDC_BOOKMARK_BAR_REMOVE
IDC_BOOKMARK_BAR_ADD_NEW_BOOKMARK = _pyautolib.IDC_BOOKMARK_BAR_ADD_NEW_BOOKMARK
IDC_BOOKMARK_BAR_NEW_FOLDER = _pyautolib.IDC_BOOKMARK_BAR_NEW_FOLDER
IDC_BOOKMARK_MANAGER = _pyautolib.IDC_BOOKMARK_MANAGER
IDC_BOOKMARK_BAR_ALWAYS_SHOW = _pyautolib.IDC_BOOKMARK_BAR_ALWAYS_SHOW
IDC_STATUS_TRAY_KEEP_CHROME_RUNNING_IN_BACKGROUND = _pyautolib.IDC_STATUS_TRAY_KEEP_CHROME_RUNNING_IN_BACKGROUND
IDR_MAINFRAME = _pyautolib.IDR_MAINFRAME
IDR_CHROMEFRAME = _pyautolib.IDR_CHROMEFRAME
IDI_THROBBER_01 = _pyautolib.IDI_THROBBER_01
IDI_THROBBER_02 = _pyautolib.IDI_THROBBER_02
IDI_THROBBER_03 = _pyautolib.IDI_THROBBER_03
IDI_THROBBER_04 = _pyautolib.IDI_THROBBER_04
IDI_THROBBER_05 = _pyautolib.IDI_THROBBER_05
IDI_THROBBER_06 = _pyautolib.IDI_THROBBER_06
IDI_THROBBER_07 = _pyautolib.IDI_THROBBER_07
IDI_THROBBER_08 = _pyautolib.IDI_THROBBER_08
IDI_THROBBER_09 = _pyautolib.IDI_THROBBER_09
IDI_THROBBER_10 = _pyautolib.IDI_THROBBER_10
IDI_THROBBER_11 = _pyautolib.IDI_THROBBER_11
IDI_THROBBER_12 = _pyautolib.IDI_THROBBER_12
IDI_THROBBER_13 = _pyautolib.IDI_THROBBER_13
IDI_THROBBER_14 = _pyautolib.IDI_THROBBER_14
IDI_THROBBER_15 = _pyautolib.IDI_THROBBER_15
IDI_THROBBER_16 = _pyautolib.IDI_THROBBER_16
IDI_THROBBER_17 = _pyautolib.IDI_THROBBER_17
IDI_THROBBER_18 = _pyautolib.IDI_THROBBER_18
IDI_THROBBER_19 = _pyautolib.IDI_THROBBER_19
IDI_THROBBER_20 = _pyautolib.IDI_THROBBER_20
IDI_THROBBER_21 = _pyautolib.IDI_THROBBER_21
IDI_THROBBER_22 = _pyautolib.IDI_THROBBER_22
IDI_THROBBER_23 = _pyautolib.IDI_THROBBER_23
IDI_THROBBER_24 = _pyautolib.IDI_THROBBER_24
IDR_SXS = _pyautolib.IDR_SXS
IDD_IPC_SETTINGS = _pyautolib.IDD_IPC_SETTINGS
kRawKeyDownType = _pyautolib.kRawKeyDownType
kKeyDownType = _pyautolib.kKeyDownType
kCharType = _pyautolib.kCharType
kKeyUpType = _pyautolib.kKeyUpType
kShiftKeyMask = _pyautolib.kShiftKeyMask
kControlKeyMask = _pyautolib.kControlKeyMask
kAltKeyMask = _pyautolib.kAltKeyMask
kMetaKeyMask = _pyautolib.kMetaKeyMask
kLeftButton = _pyautolib.kLeftButton
kMiddleButton = _pyautolib.kMiddleButton
kRightButton = _pyautolib.kRightButton
AUTOMATION_LAUNCH_RESULT_INVALID = _pyautolib.AUTOMATION_LAUNCH_RESULT_INVALID
AUTOMATION_SUCCESS = _pyautolib.AUTOMATION_SUCCESS
AUTOMATION_TIMEOUT = _pyautolib.AUTOMATION_TIMEOUT
AUTOMATION_VERSION_MISMATCH = _pyautolib.AUTOMATION_VERSION_MISMATCH
AUTOMATION_CREATE_TAB_FAILED = _pyautolib.AUTOMATION_CREATE_TAB_FAILED
AUTOMATION_SERVER_CRASHED = _pyautolib.AUTOMATION_SERVER_CRASHED
AUTOMATION_MSG_NAVIGATION_ERROR = _pyautolib.AUTOMATION_MSG_NAVIGATION_ERROR
AUTOMATION_MSG_NAVIGATION_SUCCESS = _pyautolib.AUTOMATION_MSG_NAVIGATION_SUCCESS
AUTOMATION_MSG_NAVIGATION_AUTH_NEEDED = _pyautolib.AUTOMATION_MSG_NAVIGATION_AUTH_NEEDED
AUTOMATION_MSG_EXTENSION_INSTALL_SUCCEEDED = _pyautolib.AUTOMATION_MSG_EXTENSION_INSTALL_SUCCEEDED
AUTOMATION_MSG_EXTENSION_INSTALL_FAILED = _pyautolib.AUTOMATION_MSG_EXTENSION_INSTALL_FAILED
AUTOMATION_MSG_EXTENSION_ID = _pyautolib.AUTOMATION_MSG_EXTENSION_ID
AUTOMATION_MSG_EXTENSION_NAME = _pyautolib.AUTOMATION_MSG_EXTENSION_NAME
AUTOMATION_MSG_EXTENSION_VERSION = _pyautolib.AUTOMATION_MSG_EXTENSION_VERSION
AUTOMATION_MSG_EXTENSION_BROWSER_ACTION_INDEX = _pyautolib.AUTOMATION_MSG_EXTENSION_BROWSER_ACTION_INDEX
SMALLEST_FONT = _pyautolib.SMALLEST_FONT
SMALL_FONT = _pyautolib.SMALL_FONT
MEDIUM_FONT = _pyautolib.MEDIUM_FONT
LARGE_FONT = _pyautolib.LARGE_FONT
LARGEST_FONT = _pyautolib.LARGEST_FONT
BACK = _pyautolib.BACK
FWD = _pyautolib.FWD
IGNORE_CASE = _pyautolib.IGNORE_CASE
CASE_SENSITIVE = _pyautolib.CASE_SENSITIVE
class scoped_refptr__BrowserProxy(_object):
    """Proxy of C++ scoped_refptr<(BrowserProxy)> class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, scoped_refptr__BrowserProxy, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, scoped_refptr__BrowserProxy, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> scoped_refptr__BrowserProxy
        __init__(self, BrowserProxy p) -> scoped_refptr__BrowserProxy
        """
        this = _pyautolib.new_scoped_refptr__BrowserProxy(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pyautolib.delete_scoped_refptr__BrowserProxy
    __del__ = lambda self : None;
    def get(self):
        """get(self) -> BrowserProxy"""
        return _pyautolib.scoped_refptr__BrowserProxy_get(self)

    def __deref__(self):
        """__deref__(self) -> BrowserProxy"""
        return _pyautolib.scoped_refptr__BrowserProxy___deref__(self)

    def ActivateTab(self, *args):
        """
        ActivateTab(self, int tab_index) -> bool

        Activate the tab at the given zero-based index
        """
        return _pyautolib.scoped_refptr__BrowserProxy_ActivateTab(self, *args)

    def BringToFront(self):
        """
        BringToFront(self) -> bool

        Activate the browser's window and bring it to front.
        """
        return _pyautolib.scoped_refptr__BrowserProxy_BringToFront(self)

    def GetTab(self, *args):
        """
        GetTab(self, int tab_index) -> scoped_refptr__TabProxy

        Get proxy to the tab at the given zero-based index
        """
        return _pyautolib.scoped_refptr__BrowserProxy_GetTab(self, *args)

scoped_refptr__BrowserProxy_swigregister = _pyautolib.scoped_refptr__BrowserProxy_swigregister
scoped_refptr__BrowserProxy_swigregister(scoped_refptr__BrowserProxy)
cvar = _pyautolib.cvar
kJSONProxyAutoconfig = cvar.kJSONProxyAutoconfig
kJSONProxyNoProxy = cvar.kJSONProxyNoProxy
kJSONProxyPacUrl = cvar.kJSONProxyPacUrl
kJSONProxyPacMandatory = cvar.kJSONProxyPacMandatory
kJSONProxyBypassList = cvar.kJSONProxyBypassList
kJSONProxyServer = cvar.kJSONProxyServer
kNamedInterfacePrefix = cvar.kNamedInterfacePrefix
kSleepTime = cvar.kSleepTime
kChromeDriverAutomationVersion = cvar.kChromeDriverAutomationVersion
kAppsPromoCounter = cvar.kAppsPromoCounter
kDefaultAppsInstalled = cvar.kDefaultAppsInstalled
kHomePageIsNewTabPage = cvar.kHomePageIsNewTabPage
kHomePage = cvar.kHomePage
kSessionExitedCleanly = cvar.kSessionExitedCleanly
kRestoreOnStartup = cvar.kRestoreOnStartup
kURLsToRestoreOnStartup = cvar.kURLsToRestoreOnStartup
kApplicationLocale = cvar.kApplicationLocale
kDefaultCharset = cvar.kDefaultCharset
kAcceptLanguages = cvar.kAcceptLanguages
kStaticEncodings = cvar.kStaticEncodings
kPopupWhitelistedHosts = cvar.kPopupWhitelistedHosts
kShowBookmarkBar = cvar.kShowBookmarkBar
kWebKitStandardFontFamily = cvar.kWebKitStandardFontFamily
kWebKitFixedFontFamily = cvar.kWebKitFixedFontFamily
kWebKitSerifFontFamily = cvar.kWebKitSerifFontFamily
kWebKitSansSerifFontFamily = cvar.kWebKitSansSerifFontFamily
kWebKitCursiveFontFamily = cvar.kWebKitCursiveFontFamily
kWebKitFantasyFontFamily = cvar.kWebKitFantasyFontFamily
kWebKitDefaultFontSize = cvar.kWebKitDefaultFontSize
kWebKitDefaultFixedFontSize = cvar.kWebKitDefaultFixedFontSize
kWebKitMinimumFontSize = cvar.kWebKitMinimumFontSize
kWebKitMinimumLogicalFontSize = cvar.kWebKitMinimumLogicalFontSize
kWebKitJavascriptEnabled = cvar.kWebKitJavascriptEnabled
kWebKitWebSecurityEnabled = cvar.kWebKitWebSecurityEnabled
kWebKitJavascriptCanOpenWindowsAutomatically = cvar.kWebKitJavascriptCanOpenWindowsAutomatically
kWebKitLoadsImagesAutomatically = cvar.kWebKitLoadsImagesAutomatically
kWebKitPluginsEnabled = cvar.kWebKitPluginsEnabled
kWebKitDomPasteEnabled = cvar.kWebKitDomPasteEnabled
kWebKitShrinksStandaloneImagesToFit = cvar.kWebKitShrinksStandaloneImagesToFit
kWebKitInspectorSettings = cvar.kWebKitInspectorSettings
kWebKitUsesUniversalDetector = cvar.kWebKitUsesUniversalDetector
kWebKitTextAreasAreResizable = cvar.kWebKitTextAreasAreResizable
kWebKitJavaEnabled = cvar.kWebKitJavaEnabled
kWebkitTabsToLinks = cvar.kWebkitTabsToLinks
kWebKitAllowDisplayingInsecureContent = cvar.kWebKitAllowDisplayingInsecureContent
kWebKitAllowRunningInsecureContent = cvar.kWebKitAllowRunningInsecureContent
kPasswordManagerEnabled = cvar.kPasswordManagerEnabled
kPasswordManagerAllowShowPasswords = cvar.kPasswordManagerAllowShowPasswords
kSafeBrowsingEnabled = cvar.kSafeBrowsingEnabled
kSafeBrowsingReportingEnabled = cvar.kSafeBrowsingReportingEnabled
kIncognitoEnabled = cvar.kIncognitoEnabled
kSearchSuggestEnabled = cvar.kSearchSuggestEnabled
kConfirmToQuitEnabled = cvar.kConfirmToQuitEnabled
kCookieBehavior = cvar.kCookieBehavior
kDefaultSearchProviderEnabled = cvar.kDefaultSearchProviderEnabled
kDefaultSearchProviderSearchURL = cvar.kDefaultSearchProviderSearchURL
kDefaultSearchProviderSuggestURL = cvar.kDefaultSearchProviderSuggestURL
kDefaultSearchProviderInstantURL = cvar.kDefaultSearchProviderInstantURL
kDefaultSearchProviderIconURL = cvar.kDefaultSearchProviderIconURL
kDefaultSearchProviderEncodings = cvar.kDefaultSearchProviderEncodings
kDefaultSearchProviderName = cvar.kDefaultSearchProviderName
kDefaultSearchProviderKeyword = cvar.kDefaultSearchProviderKeyword
kDefaultSearchProviderID = cvar.kDefaultSearchProviderID
kDefaultSearchProviderPrepopulateID = cvar.kDefaultSearchProviderPrepopulateID
kSearchProviderOverrides = cvar.kSearchProviderOverrides
kSearchProviderOverridesVersion = cvar.kSearchProviderOverridesVersion
kPromptForDownload = cvar.kPromptForDownload
kAlternateErrorPagesEnabled = cvar.kAlternateErrorPagesEnabled
kDnsStartupPrefetchList = cvar.kDnsStartupPrefetchList
kDnsPrefetchingStartupList = cvar.kDnsPrefetchingStartupList
kDnsHostReferralList = cvar.kDnsHostReferralList
kDnsPrefetchingHostReferralList = cvar.kDnsPrefetchingHostReferralList
kDisableSpdy = cvar.kDisableSpdy
kDisabledSchemes = cvar.kDisabledSchemes
kInstantConfirmDialogShown = cvar.kInstantConfirmDialogShown
kInstantEnabled = cvar.kInstantEnabled
kInstantEnabledOnce = cvar.kInstantEnabledOnce
kInstantEnabledTime = cvar.kInstantEnabledTime
kInstantPromo = cvar.kInstantPromo
kMultipleProfilePrefMigration = cvar.kMultipleProfilePrefMigration
kNetworkPredictionEnabled = cvar.kNetworkPredictionEnabled
kIpcDisabledMessages = cvar.kIpcDisabledMessages
kShowHomeButton = cvar.kShowHomeButton
kRecentlySelectedEncoding = cvar.kRecentlySelectedEncoding
kDeleteBrowsingHistory = cvar.kDeleteBrowsingHistory
kDeleteDownloadHistory = cvar.kDeleteDownloadHistory
kDeleteCache = cvar.kDeleteCache
kDeleteCookies = cvar.kDeleteCookies
kDeletePasswords = cvar.kDeletePasswords
kDeleteFormData = cvar.kDeleteFormData
kEnableSpellCheck = cvar.kEnableSpellCheck
kEnabledLabsExperiments = cvar.kEnabledLabsExperiments
kEnableAutoSpellCorrect = cvar.kEnableAutoSpellCorrect
kSavingBrowserHistoryDisabled = cvar.kSavingBrowserHistoryDisabled
kDeleteTimePeriod = cvar.kDeleteTimePeriod
kPrintingEnabled = cvar.kPrintingEnabled
kPrintingPageHeaderLeft = cvar.kPrintingPageHeaderLeft
kPrintingPageHeaderCenter = cvar.kPrintingPageHeaderCenter
kPrintingPageHeaderRight = cvar.kPrintingPageHeaderRight
kPrintingPageFooterLeft = cvar.kPrintingPageFooterLeft
kPrintingPageFooterCenter = cvar.kPrintingPageFooterCenter
kPrintingPageFooterRight = cvar.kPrintingPageFooterRight
kCurrentThemePackFilename = cvar.kCurrentThemePackFilename
kCurrentThemeID = cvar.kCurrentThemeID
kCurrentThemeImages = cvar.kCurrentThemeImages
kCurrentThemeColors = cvar.kCurrentThemeColors
kCurrentThemeTints = cvar.kCurrentThemeTints
kCurrentThemeDisplayProperties = cvar.kCurrentThemeDisplayProperties
kExtensionsUIDeveloperMode = cvar.kExtensionsUIDeveloperMode
kExtensionToolbarSize = cvar.kExtensionToolbarSize
kPluginsLastInternalDirectory = cvar.kPluginsLastInternalDirectory
kPluginsPluginsList = cvar.kPluginsPluginsList
kPluginsDisabledPlugins = cvar.kPluginsDisabledPlugins
kPluginsDisabledPluginsExceptions = cvar.kPluginsDisabledPluginsExceptions
kPluginsEnabledPlugins = cvar.kPluginsEnabledPlugins
kPluginsEnabledInternalPDF = cvar.kPluginsEnabledInternalPDF
kPluginsShowSetReaderDefaultInfobar = cvar.kPluginsShowSetReaderDefaultInfobar
kPluginsShowDetails = cvar.kPluginsShowDetails
kPluginsAllowOutdated = cvar.kPluginsAllowOutdated
kPluginsAlwaysAuthorize = cvar.kPluginsAlwaysAuthorize
kCheckDefaultBrowser = cvar.kCheckDefaultBrowser
kDefaultBrowserSettingEnabled = cvar.kDefaultBrowserSettingEnabled
kUseCustomChromeFrame = cvar.kUseCustomChromeFrame
kShowOmniboxSearchHint = cvar.kShowOmniboxSearchHint
kDesktopNotificationDefaultContentSetting = cvar.kDesktopNotificationDefaultContentSetting
kDesktopNotificationAllowedOrigins = cvar.kDesktopNotificationAllowedOrigins
kDesktopNotificationDeniedOrigins = cvar.kDesktopNotificationDeniedOrigins
kDesktopNotificationPosition = cvar.kDesktopNotificationPosition
kDefaultContentSettings = cvar.kDefaultContentSettings
kPerHostContentSettings = cvar.kPerHostContentSettings
kContentSettingsVersion = cvar.kContentSettingsVersion
kContentSettingsPatterns = cvar.kContentSettingsPatterns
kBlockThirdPartyCookies = cvar.kBlockThirdPartyCookies
kClearSiteDataOnExit = cvar.kClearSiteDataOnExit
kDefaultZoomLevel = cvar.kDefaultZoomLevel
kPerHostZoomLevels = cvar.kPerHostZoomLevels
kAutofillEnabled = cvar.kAutofillEnabled
kAutofillAuxiliaryProfilesEnabled = cvar.kAutofillAuxiliaryProfilesEnabled
kAutofillDialogPlacement = cvar.kAutofillDialogPlacement
kAutofillPositiveUploadRate = cvar.kAutofillPositiveUploadRate
kAutofillNegativeUploadRate = cvar.kAutofillNegativeUploadRate
kAutofillPersonalDataManagerFirstRun = cvar.kAutofillPersonalDataManagerFirstRun
kEditBookmarksEnabled = cvar.kEditBookmarksEnabled
kUseVerticalTabs = cvar.kUseVerticalTabs
kUseCompactNavigationBar = cvar.kUseCompactNavigationBar
kEnableTranslate = cvar.kEnableTranslate
kEnableBookmarkBar = cvar.kEnableBookmarkBar
kPinnedTabs = cvar.kPinnedTabs
kHttpThrottlingEnabled = cvar.kHttpThrottlingEnabled
kDisable3DAPIs = cvar.kDisable3DAPIs
kEnableHyperlinkAuditing = cvar.kEnableHyperlinkAuditing
kEnableReferrers = cvar.kEnableReferrers
kCertRevocationCheckingEnabled = cvar.kCertRevocationCheckingEnabled
kSSL3Enabled = cvar.kSSL3Enabled
kTLS1Enabled = cvar.kTLS1Enabled
kMetricsClientID = cvar.kMetricsClientID
kMetricsSessionID = cvar.kMetricsSessionID
kMetricsClientIDTimestamp = cvar.kMetricsClientIDTimestamp
kMetricsReportingEnabled = cvar.kMetricsReportingEnabled
kMetricsInitialLogs = cvar.kMetricsInitialLogs
kMetricsOngoingLogs = cvar.kMetricsOngoingLogs
kProfileLastUsed = cvar.kProfileLastUsed
kProfileDirectoryMap = cvar.kProfileDirectoryMap
kProfilesNumCreated = cvar.kProfilesNumCreated
kProfileMetrics = cvar.kProfileMetrics
kProfilePrefix = cvar.kProfilePrefix
kStabilityExitedCleanly = cvar.kStabilityExitedCleanly
kStabilityStatsVersion = cvar.kStabilityStatsVersion
kStabilityStatsBuildTime = cvar.kStabilityStatsBuildTime
kStabilitySessionEndCompleted = cvar.kStabilitySessionEndCompleted
kStabilityLaunchCount = cvar.kStabilityLaunchCount
kStabilityCrashCount = cvar.kStabilityCrashCount
kStabilityIncompleteSessionEndCount = cvar.kStabilityIncompleteSessionEndCount
kStabilityPageLoadCount = cvar.kStabilityPageLoadCount
kStabilityRendererCrashCount = cvar.kStabilityRendererCrashCount
kStabilityExtensionRendererCrashCount = cvar.kStabilityExtensionRendererCrashCount
kStabilityLaunchTimeSec = cvar.kStabilityLaunchTimeSec
kStabilityLastTimestampSec = cvar.kStabilityLastTimestampSec
kStabilityRendererHangCount = cvar.kStabilityRendererHangCount
kStabilityChildProcessCrashCount = cvar.kStabilityChildProcessCrashCount
kStabilityOtherUserCrashCount = cvar.kStabilityOtherUserCrashCount
kStabilityKernelCrashCount = cvar.kStabilityKernelCrashCount
kStabilitySystemUncleanShutdownCount = cvar.kStabilitySystemUncleanShutdownCount
kStabilityBreakpadRegistrationSuccess = cvar.kStabilityBreakpadRegistrationSuccess
kStabilityBreakpadRegistrationFail = cvar.kStabilityBreakpadRegistrationFail
kStabilityDebuggerPresent = cvar.kStabilityDebuggerPresent
kStabilityDebuggerNotPresent = cvar.kStabilityDebuggerNotPresent
kStabilityPluginStats = cvar.kStabilityPluginStats
kStabilityPluginName = cvar.kStabilityPluginName
kStabilityPluginLaunches = cvar.kStabilityPluginLaunches
kStabilityPluginInstances = cvar.kStabilityPluginInstances
kStabilityPluginCrashes = cvar.kStabilityPluginCrashes
kUninstallMetricsPageLoadCount = cvar.kUninstallMetricsPageLoadCount
kUninstallLaunchCount = cvar.kUninstallLaunchCount
kUninstallMetricsInstallDate = cvar.kUninstallMetricsInstallDate
kUninstallMetricsUptimeSec = cvar.kUninstallMetricsUptimeSec
kUninstallLastLaunchTimeSec = cvar.kUninstallLastLaunchTimeSec
kUninstallLastObservedRunTimeSec = cvar.kUninstallLastObservedRunTimeSec
kBrowserWindowPlacement = cvar.kBrowserWindowPlacement
kTaskManagerWindowPlacement = cvar.kTaskManagerWindowPlacement
kKeywordEditorWindowPlacement = cvar.kKeywordEditorWindowPlacement
kPreferencesWindowPlacement = cvar.kPreferencesWindowPlacement
kMemoryCacheSize = cvar.kMemoryCacheSize
kDownloadDefaultDirectory = cvar.kDownloadDefaultDirectory
kDownloadExtensionsToOpen = cvar.kDownloadExtensionsToOpen
kDownloadDirUpgraded = cvar.kDownloadDirUpgraded
kSaveFileDefaultDirectory = cvar.kSaveFileDefaultDirectory
kSaveFileType = cvar.kSaveFileType
kAllowFileSelectionDialogs = cvar.kAllowFileSelectionDialogs
kSelectFileLastDirectory = cvar.kSelectFileLastDirectory
kHungPluginDetectFrequency = cvar.kHungPluginDetectFrequency
kPluginMessageResponseTimeout = cvar.kPluginMessageResponseTimeout
kSpellCheckDictionary = cvar.kSpellCheckDictionary
kExcludedSchemes = cvar.kExcludedSchemes
kSafeBrowsingClientKey = cvar.kSafeBrowsingClientKey
kSafeBrowsingWrappedKey = cvar.kSafeBrowsingWrappedKey
kOptionsWindowLastTabIndex = cvar.kOptionsWindowLastTabIndex
kContentSettingsWindowLastTabIndex = cvar.kContentSettingsWindowLastTabIndex
kCertificateManagerWindowLastTabIndex = cvar.kCertificateManagerWindowLastTabIndex
kShouldShowFirstRunBubble = cvar.kShouldShowFirstRunBubble
kShouldUseOEMFirstRunBubble = cvar.kShouldUseOEMFirstRunBubble
kShouldUseMinimalFirstRunBubble = cvar.kShouldUseMinimalFirstRunBubble
kShouldShowWelcomePage = cvar.kShouldShowWelcomePage
kLastKnownGoogleURL = cvar.kLastKnownGoogleURL
kLastPromptedGoogleURL = cvar.kLastPromptedGoogleURL
kLastKnownIntranetRedirectOrigin = cvar.kLastKnownIntranetRedirectOrigin
kCountryIDAtInstall = cvar.kCountryIDAtInstall
kGeoIDAtInstall = cvar.kGeoIDAtInstall
kShutdownType = cvar.kShutdownType
kShutdownNumProcesses = cvar.kShutdownNumProcesses
kShutdownNumProcessesSlow = cvar.kShutdownNumProcessesSlow
kRestartLastSessionOnShutdown = cvar.kRestartLastSessionOnShutdown
kNumBookmarksOnBookmarkBar = cvar.kNumBookmarksOnBookmarkBar
kNumFoldersOnBookmarkBar = cvar.kNumFoldersOnBookmarkBar
kNumBookmarksInOtherBookmarkFolder = cvar.kNumBookmarksInOtherBookmarkFolder
kNumFoldersInOtherBookmarkFolder = cvar.kNumFoldersInOtherBookmarkFolder
kNumKeywords = cvar.kNumKeywords
kDisableVideoAndChat = cvar.kDisableVideoAndChat
kDisableExtensions = cvar.kDisableExtensions
kDisablePluginFinder = cvar.kDisablePluginFinder
kBrowserActionContainerWidth = cvar.kBrowserActionContainerWidth
kLastExtensionsUpdateCheck = cvar.kLastExtensionsUpdateCheck
kNextExtensionsUpdateCheck = cvar.kNextExtensionsUpdateCheck
kExtensionInstallAllowList = cvar.kExtensionInstallAllowList
kExtensionInstallDenyList = cvar.kExtensionInstallDenyList
kExtensionInstallForceList = cvar.kExtensionInstallForceList
kExtensionBlacklistUpdateVersion = cvar.kExtensionBlacklistUpdateVersion
kExtensionSidebarWidth = cvar.kExtensionSidebarWidth
kNTPTipsResourceServer = cvar.kNTPTipsResourceServer
kNTPMostVisitedURLsBlacklist = cvar.kNTPMostVisitedURLsBlacklist
kNTPMostVisitedPinnedURLs = cvar.kNTPMostVisitedPinnedURLs
kNTPPromoResourceCache = cvar.kNTPPromoResourceCache
kNTPPromoResourceCacheUpdate = cvar.kNTPPromoResourceCacheUpdate
kNTPPromoResourceServer = cvar.kNTPPromoResourceServer
kNTPDateResourceServer = cvar.kNTPDateResourceServer
kNTPShownSections = cvar.kNTPShownSections
kNTPPrefVersion = cvar.kNTPPrefVersion
kNTPCustomLogoStart = cvar.kNTPCustomLogoStart
kNTPCustomLogoEnd = cvar.kNTPCustomLogoEnd
kNTPPromoVersion = cvar.kNTPPromoVersion
kNTPPromoLocale = cvar.kNTPPromoLocale
kNTPPromoStart = cvar.kNTPPromoStart
kNTPPromoEnd = cvar.kNTPPromoEnd
kNTPPromoLine = cvar.kNTPPromoLine
kNTPPromoClosed = cvar.kNTPPromoClosed
kNTPPromoGroup = cvar.kNTPPromoGroup
kNTPPromoGroupTimeSlice = cvar.kNTPPromoGroupTimeSlice
kNTPPromoBuild = cvar.kNTPPromoBuild
kNTPWebStoreEnabled = cvar.kNTPWebStoreEnabled
kNTPWebStorePromoLastId = cvar.kNTPWebStorePromoLastId
kNTPWebStorePromoId = cvar.kNTPWebStorePromoId
kNTPWebStorePromoHeader = cvar.kNTPWebStorePromoHeader
kNTPWebStorePromoButton = cvar.kNTPWebStorePromoButton
kNTPWebStorePromoLink = cvar.kNTPWebStorePromoLink
kNTPWebStorePromoLogo = cvar.kNTPWebStorePromoLogo
kNTPWebStorePromoExpire = cvar.kNTPWebStorePromoExpire
kNTPWebStorePromoUserGroup = cvar.kNTPWebStorePromoUserGroup
kGpuBlacklist = cvar.kGpuBlacklist
kGpuBlacklistUpdate = cvar.kGpuBlacklistUpdate
kDevToolsDisabled = cvar.kDevToolsDisabled
kDevToolsOpenDocked = cvar.kDevToolsOpenDocked
kDevToolsSplitLocation = cvar.kDevToolsSplitLocation
kSyncSessions = cvar.kSyncSessions
kSyncLastSyncedTime = cvar.kSyncLastSyncedTime
kSyncHasSetupCompleted = cvar.kSyncHasSetupCompleted
kKeepEverythingSynced = cvar.kKeepEverythingSynced
kSyncBookmarks = cvar.kSyncBookmarks
kSyncPasswords = cvar.kSyncPasswords
kSyncPreferences = cvar.kSyncPreferences
kSyncApps = cvar.kSyncApps
kSyncAutofill = cvar.kSyncAutofill
kSyncAutofillProfile = cvar.kSyncAutofillProfile
kSyncThemes = cvar.kSyncThemes
kSyncTypedUrls = cvar.kSyncTypedUrls
kSyncExtensions = cvar.kSyncExtensions
kSyncManaged = cvar.kSyncManaged
kSyncSuppressStart = cvar.kSyncSuppressStart
kGoogleServicesUsername = cvar.kGoogleServicesUsername
kSyncUsingSecondaryPassphrase = cvar.kSyncUsingSecondaryPassphrase
kEncryptionBootstrapToken = cvar.kEncryptionBootstrapToken
kAutofillProfileMigrated = cvar.kAutofillProfileMigrated
kWebAppCreateOnDesktop = cvar.kWebAppCreateOnDesktop
kWebAppCreateInAppsMenu = cvar.kWebAppCreateInAppsMenu
kWebAppCreateInQuickLaunchBar = cvar.kWebAppCreateInQuickLaunchBar
kGeolocationAccessToken = cvar.kGeolocationAccessToken
kGeolocationDefaultContentSetting = cvar.kGeolocationDefaultContentSetting
kGeolocationContentSettings = cvar.kGeolocationContentSettings
kLoginDatabaseMigrated = cvar.kLoginDatabaseMigrated
kCloudPrintServiceURL = cvar.kCloudPrintServiceURL
kCloudPrintDialogWidth = cvar.kCloudPrintDialogWidth
kCloudPrintDialogHeight = cvar.kCloudPrintDialogHeight
kCloudPrintProxyEnabled = cvar.kCloudPrintProxyEnabled
kCloudPrintProxyId = cvar.kCloudPrintProxyId
kCloudPrintAuthToken = cvar.kCloudPrintAuthToken
kCloudPrintXMPPAuthToken = cvar.kCloudPrintXMPPAuthToken
kCloudPrintEmail = cvar.kCloudPrintEmail
kCloudPrintPrintSystemSettings = cvar.kCloudPrintPrintSystemSettings
kCloudPrintEnableJobPoll = cvar.kCloudPrintEnableJobPoll
kCloudPrintRobotRefreshToken = cvar.kCloudPrintRobotRefreshToken
kCloudPrintRobotEmail = cvar.kCloudPrintRobotEmail
kProxy = cvar.kProxy
kManagedDefaultCookiesSetting = cvar.kManagedDefaultCookiesSetting
kManagedDefaultImagesSetting = cvar.kManagedDefaultImagesSetting
kManagedDefaultJavaScriptSetting = cvar.kManagedDefaultJavaScriptSetting
kManagedDefaultPluginsSetting = cvar.kManagedDefaultPluginsSetting
kManagedDefaultPopupsSetting = cvar.kManagedDefaultPopupsSetting
kManagedCookiesAllowedForUrls = cvar.kManagedCookiesAllowedForUrls
kManagedCookiesBlockedForUrls = cvar.kManagedCookiesBlockedForUrls
kManagedCookiesSessionOnlyForUrls = cvar.kManagedCookiesSessionOnlyForUrls
kManagedImagesAllowedForUrls = cvar.kManagedImagesAllowedForUrls
kManagedImagesBlockedForUrls = cvar.kManagedImagesBlockedForUrls
kManagedJavaScriptAllowedForUrls = cvar.kManagedJavaScriptAllowedForUrls
kManagedJavaScriptBlockedForUrls = cvar.kManagedJavaScriptBlockedForUrls
kManagedPluginsAllowedForUrls = cvar.kManagedPluginsAllowedForUrls
kManagedPluginsBlockedForUrls = cvar.kManagedPluginsBlockedForUrls
kManagedPopupsAllowedForUrls = cvar.kManagedPopupsAllowedForUrls
kManagedPopupsBlockedForUrls = cvar.kManagedPopupsBlockedForUrls
kClearPluginLSODataEnabled = cvar.kClearPluginLSODataEnabled
kDiskCacheDir = cvar.kDiskCacheDir
kRegisteredBackgroundContents = cvar.kRegisteredBackgroundContents
kAuthSchemes = cvar.kAuthSchemes
kDisableAuthNegotiateCnameLookup = cvar.kDisableAuthNegotiateCnameLookup
kEnableAuthNegotiatePort = cvar.kEnableAuthNegotiatePort
kAuthServerWhitelist = cvar.kAuthServerWhitelist
kAuthNegotiateDelegateWhitelist = cvar.kAuthNegotiateDelegateWhitelist
kGSSAPILibraryName = cvar.kGSSAPILibraryName
kAllowCrossOriginAuthPrompt = cvar.kAllowCrossOriginAuthPrompt
kRegisteredProtocolHandlers = cvar.kRegisteredProtocolHandlers
kIgnoredProtocolHandlers = cvar.kIgnoredProtocolHandlers
kCustomHandlersEnabled = cvar.kCustomHandlersEnabled
kUserCreatedLoginItem = cvar.kUserCreatedLoginItem
kBackgroundModeEnabled = cvar.kBackgroundModeEnabled
kDevicePolicyRefreshRate = cvar.kDevicePolicyRefreshRate
kUserPolicyRefreshRate = cvar.kUserPolicyRefreshRate

class scoped_refptr__TabProxy(_object):
    """Proxy of C++ scoped_refptr<(TabProxy)> class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, scoped_refptr__TabProxy, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, scoped_refptr__TabProxy, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> scoped_refptr__TabProxy
        __init__(self, TabProxy p) -> scoped_refptr__TabProxy
        """
        this = _pyautolib.new_scoped_refptr__TabProxy(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pyautolib.delete_scoped_refptr__TabProxy
    __del__ = lambda self : None;
    def get(self):
        """get(self) -> TabProxy"""
        return _pyautolib.scoped_refptr__TabProxy_get(self)

    def __deref__(self):
        """__deref__(self) -> TabProxy"""
        return _pyautolib.scoped_refptr__TabProxy___deref__(self)

    def NavigateToURL(self, *args):
        """
        NavigateToURL(self, GURL url) -> AutomationMsg_NavigationResponseValues

        Navigates to a given GURL. Blocks until the navigation completes. 
        """
        return _pyautolib.scoped_refptr__TabProxy_NavigateToURL(self, *args)

    def NavigateToURLBlockUntilNavigationsComplete(self, *args):
        """
        NavigateToURLBlockUntilNavigationsComplete(self, GURL url, int number_of_navigations) -> AutomationMsg_NavigationResponseValues

        Navigates to a given GURL. Blocks until the given number of navigations complete.
        """
        return _pyautolib.scoped_refptr__TabProxy_NavigateToURLBlockUntilNavigationsComplete(self, *args)

    def NavigateToURLAsync(self, *args):
        """
        NavigateToURLAsync(self, GURL url) -> bool

        Navigates to a given GURL asynchronously. Does not wait for the navigation to complete, or even begin; Use NavigateToURL() if you want to wait.
        """
        return _pyautolib.scoped_refptr__TabProxy_NavigateToURLAsync(self, *args)

    def GoBack(self):
        """
        GoBack(self) -> AutomationMsg_NavigationResponseValues

        Equivalent to hitting the Back button. Blocks until navigation completes.
        """
        return _pyautolib.scoped_refptr__TabProxy_GoBack(self)

    def GoForward(self):
        """
        GoForward(self) -> AutomationMsg_NavigationResponseValues

        Equivalent to hitting the Forward button. Blocks until navigation completes.
        """
        return _pyautolib.scoped_refptr__TabProxy_GoForward(self)

    def Reload(self):
        """
        Reload(self) -> AutomationMsg_NavigationResponseValues

        Equivalent to hitting the Reload button. Blocks until navigation completes.
        """
        return _pyautolib.scoped_refptr__TabProxy_Reload(self)

    def Close(self, *args):
        """
        Close(self) -> bool
        Close(self, bool wait_until_closed) -> bool

        Closes the tab. Supply True to wait until the tab has closed, else it'll wait only until the call has been initiated. Be careful while closing the last tab since it might close the browser.
        """
        return _pyautolib.scoped_refptr__TabProxy_Close(self, *args)

    def WaitForTabToBeRestored(self, *args):
        """
        WaitForTabToBeRestored(self, uint32 timeout_ms) -> bool

        Blocks until tab is completely restored.
        """
        return _pyautolib.scoped_refptr__TabProxy_WaitForTabToBeRestored(self, *args)

    def NeedsAuth(self):
        """
        NeedsAuth(self) -> bool

        Checks if this tab has a login prompt waiting for auth.  This will be true if a navigation results in a login prompt, and if an attempted login fails. Note that this is only valid if you've done a navigation on this same object; different TabProxy objects can refer to the same Tab.  Calls that can set this are NavigateToURL, GoBack, and GoForward. 
        """
        return _pyautolib.scoped_refptr__TabProxy_NeedsAuth(self)

    def SetAuth(self, *args):
        """
        SetAuth(self, wstring username, wstring password) -> bool

        Supply authentication to a login prompt. Blocks until navigation completes or another login prompt appears in the case of failed auth.
        """
        return _pyautolib.scoped_refptr__TabProxy_SetAuth(self, *args)

    def CancelAuth(self):
        """
        CancelAuth(self) -> bool

        Cancel authentication to a login prompt. 
        """
        return _pyautolib.scoped_refptr__TabProxy_CancelAuth(self)

scoped_refptr__TabProxy_swigregister = _pyautolib.scoped_refptr__TabProxy_swigregister
scoped_refptr__TabProxy_swigregister(scoped_refptr__TabProxy)

class GURL(_object):
    """Represent a URL. Call spec() to get the string."""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GURL, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GURL, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> GURL
        __init__(self, string url_string) -> GURL

        Represent a URL. Call spec() to get the string.
        """
        this = _pyautolib.new_GURL(*args)
        try: self.this.append(this)
        except: self.this = this
    def spec(self):
        """
        spec(self) -> string

        Get the string representation.
        """
        return _pyautolib.GURL_spec(self)

    __swig_destroy__ = _pyautolib.delete_GURL
    __del__ = lambda self : None;
GURL_swigregister = _pyautolib.GURL_swigregister
GURL_swigregister(GURL)

class FilePath(_object):
    """Represent a file path. Call value() to get the string."""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FilePath, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FilePath, name)
    __repr__ = _swig_repr
    def value(self):
        """
        value(self) -> StringType

        Get the string representation.
        """
        return _pyautolib.FilePath_value(self)

    def __init__(self, *args): 
        """
        __init__(self) -> FilePath
        __init__(self, StringType path) -> FilePath

        Construct an empty FilePath from a string.
        """
        this = _pyautolib.new_FilePath(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pyautolib.delete_FilePath
    __del__ = lambda self : None;
FilePath_swigregister = _pyautolib.FilePath_swigregister
FilePath_swigregister(FilePath)

class BrowserProxy(_object):
    """Proxy handle to a browser window."""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BrowserProxy, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BrowserProxy, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def ActivateTab(self, *args):
        """
        ActivateTab(self, int tab_index) -> bool

        Activate the tab at the given zero-based index
        """
        return _pyautolib.BrowserProxy_ActivateTab(self, *args)

    def BringToFront(self):
        """
        BringToFront(self) -> bool

        Activate the browser's window and bring it to front.
        """
        return _pyautolib.BrowserProxy_BringToFront(self)

    def GetTab(self, *args):
        """
        GetTab(self, int tab_index) -> scoped_refptr__TabProxy

        Get proxy to the tab at the given zero-based index
        """
        return _pyautolib.BrowserProxy_GetTab(self, *args)

BrowserProxy_swigregister = _pyautolib.BrowserProxy_swigregister
BrowserProxy_swigregister(BrowserProxy)

class TabProxy(_object):
    """Proxy handle to a tab."""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TabProxy, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TabProxy, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def NavigateToURL(self, *args):
        """
        NavigateToURL(self, GURL url) -> AutomationMsg_NavigationResponseValues

        Navigates to a given GURL. Blocks until the navigation completes. 
        """
        return _pyautolib.TabProxy_NavigateToURL(self, *args)

    def NavigateToURLBlockUntilNavigationsComplete(self, *args):
        """
        NavigateToURLBlockUntilNavigationsComplete(self, GURL url, int number_of_navigations) -> AutomationMsg_NavigationResponseValues

        Navigates to a given GURL. Blocks until the given number of navigations complete.
        """
        return _pyautolib.TabProxy_NavigateToURLBlockUntilNavigationsComplete(self, *args)

    def NavigateToURLAsync(self, *args):
        """
        NavigateToURLAsync(self, GURL url) -> bool

        Navigates to a given GURL asynchronously. Does not wait for the navigation to complete, or even begin; Use NavigateToURL() if you want to wait.
        """
        return _pyautolib.TabProxy_NavigateToURLAsync(self, *args)

    def GoBack(self):
        """
        GoBack(self) -> AutomationMsg_NavigationResponseValues

        Equivalent to hitting the Back button. Blocks until navigation completes.
        """
        return _pyautolib.TabProxy_GoBack(self)

    def GoForward(self):
        """
        GoForward(self) -> AutomationMsg_NavigationResponseValues

        Equivalent to hitting the Forward button. Blocks until navigation completes.
        """
        return _pyautolib.TabProxy_GoForward(self)

    def Reload(self):
        """
        Reload(self) -> AutomationMsg_NavigationResponseValues

        Equivalent to hitting the Reload button. Blocks until navigation completes.
        """
        return _pyautolib.TabProxy_Reload(self)

    def Close(self, *args):
        """
        Close(self) -> bool
        Close(self, bool wait_until_closed) -> bool

        Closes the tab. Supply True to wait until the tab has closed, else it'll wait only until the call has been initiated. Be careful while closing the last tab since it might close the browser.
        """
        return _pyautolib.TabProxy_Close(self, *args)

    def WaitForTabToBeRestored(self, *args):
        """
        WaitForTabToBeRestored(self, uint32 timeout_ms) -> bool

        Blocks until tab is completely restored.
        """
        return _pyautolib.TabProxy_WaitForTabToBeRestored(self, *args)

    def NeedsAuth(self):
        """
        NeedsAuth(self) -> bool

        Checks if this tab has a login prompt waiting for auth.  This will be true if a navigation results in a login prompt, and if an attempted login fails. Note that this is only valid if you've done a navigation on this same object; different TabProxy objects can refer to the same Tab.  Calls that can set this are NavigateToURL, GoBack, and GoForward. 
        """
        return _pyautolib.TabProxy_NeedsAuth(self)

    def SetAuth(self, *args):
        """
        SetAuth(self, wstring username, wstring password) -> bool

        Supply authentication to a login prompt. Blocks until navigation completes or another login prompt appears in the case of failed auth.
        """
        return _pyautolib.TabProxy_SetAuth(self, *args)

    def CancelAuth(self):
        """
        CancelAuth(self) -> bool

        Cancel authentication to a login prompt. 
        """
        return _pyautolib.TabProxy_CancelAuth(self)

TabProxy_swigregister = _pyautolib.TabProxy_swigregister
TabProxy_swigregister(TabProxy)

class PyUITestSuiteBase(_object):
    """Proxy of C++ PyUITestSuiteBase class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PyUITestSuiteBase, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PyUITestSuiteBase, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self, int argc) -> PyUITestSuiteBase

        Create the suite.
        """
        this = _pyautolib.new_PyUITestSuiteBase(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pyautolib.delete_PyUITestSuiteBase
    __del__ = lambda self : None;
    def InitializeWithPath(self, *args):
        """
        InitializeWithPath(self, FilePath browser_dir)

        Initialize from the path to browser dir.
        """
        return _pyautolib.PyUITestSuiteBase_InitializeWithPath(self, *args)

    def SetCrSourceRoot(self, *args):
        """
        SetCrSourceRoot(self, FilePath path)

        Set chrome source root path, used in some tests
        """
        return _pyautolib.PyUITestSuiteBase_SetCrSourceRoot(self, *args)

PyUITestSuiteBase_swigregister = _pyautolib.PyUITestSuiteBase_swigregister
PyUITestSuiteBase_swigregister(PyUITestSuiteBase)

class PyUITestBase(_object):
    """Proxy of C++ PyUITestBase class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PyUITestBase, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PyUITestBase, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, bool clear_profile, wstring homepage) -> PyUITestBase"""
        this = _pyautolib.new_PyUITestBase(*args)
        try: self.this.append(this)
        except: self.this = this
    def Initialize(self, *args):
        """
        Initialize(self, FilePath browser_dir)

        Initialize the entire setup. Should be called before launching the browser. For internal use.
        """
        return _pyautolib.PyUITestBase_Initialize(self, *args)

    def UseNamedChannelID(self, *args):
        """UseNamedChannelID(self, string named_channel_id)"""
        return _pyautolib.PyUITestBase_UseNamedChannelID(self, *args)

    def SetUp(self):
        """
        SetUp(self)

        Fires up the browser and opens a window.
        """
        return _pyautolib.PyUITestBase_SetUp(self)

    def TearDown(self):
        """
        TearDown(self)

        Closes all windows and destroys the browser.
        """
        return _pyautolib.PyUITestBase_TearDown(self)

    def action_max_timeout_ms(self):
        """
        action_max_timeout_ms(self) -> int

        Timeout (in milli secs) for an action. This value is also used as default for the WaitUntil() method.
        """
        return _pyautolib.PyUITestBase_action_max_timeout_ms(self)

    def action_timeout_ms(self):
        """
        action_timeout_ms(self) -> int

        Get the timeout (in milli secs) for an automation call
        """
        return _pyautolib.PyUITestBase_action_timeout_ms(self)

    def set_action_timeout_ms(self, *args):
        """
        set_action_timeout_ms(self, int timeout)

        Set the timeout (in milli secs) for an automation call.  This is an internal method.  Do not use this directly.  Use ActionTimeoutChanger instead
        """
        return _pyautolib.PyUITestBase_set_action_timeout_ms(self, *args)

    def large_test_timeout_ms(self):
        """
        large_test_timeout_ms(self) -> int

        Timeout (in milli secs) for large tests.
        """
        return _pyautolib.PyUITestBase_large_test_timeout_ms(self)

    def LaunchBrowserAndServer(self):
        """
        LaunchBrowserAndServer(self)

        Launches the browser and IPC testing server.
        """
        return _pyautolib.PyUITestBase_LaunchBrowserAndServer(self)

    def CloseBrowserAndServer(self):
        """
        CloseBrowserAndServer(self)

        Closes the browser and IPC testing server.
        """
        return _pyautolib.PyUITestBase_CloseBrowserAndServer(self)

    def get_clear_profile(self):
        """
        get_clear_profile(self) -> bool

        Determine if the profile is set to be cleared on next startup.
        """
        return _pyautolib.PyUITestBase_get_clear_profile(self)

    def set_clear_profile(self, *args):
        """
        set_clear_profile(self, bool clear_profile)

        If False, sets the flag so that the profile is not cleared on next startup. Useful for persisting profile across restarts. By default the state is True, to clear profile.
        """
        return _pyautolib.PyUITestBase_set_clear_profile(self, *args)

    def NavigateToURL(self, *args):
        """
        NavigateToURL(self, char url_string)
        NavigateToURL(self, char url_string, int window_index)
        NavigateToURL(self, char url_string, int window_index, int tab_index)

        Navigate to the given url in the given tab and given window (or active tab in first window if indexes not given). Note that this method also activates the corresponding tab/window if it's not active already. Blocks until page has loaded.
        """
        return _pyautolib.PyUITestBase_NavigateToURL(self, *args)

    def ReloadActiveTab(self, window_index = 0):
        """
        ReloadActiveTab(self, int window_index = 0)
        ReloadActiveTab(self)

        Reload the active tab in the given window (or first window if index not given). Blocks until page has reloaded.
        """
        return _pyautolib.PyUITestBase_ReloadActiveTab(self, window_index)

    def ApplyAccelerator(self, *args):
        """
        ApplyAccelerator(self, int id, int window_index = 0) -> bool
        ApplyAccelerator(self, int id) -> bool

        Apply the accelerator with given id (IDC_BACK, IDC_NEWTAB ...) to the given or first window. The list can be found at chrome/app/chrome_dll_resource.h. Note that this method just schedules the accelerator, but does not wait for it to actually finish doing anything.Returns True on success.
        """
        return _pyautolib.PyUITestBase_ApplyAccelerator(self, *args)

    def RunCommand(self, *args):
        """
        RunCommand(self, int browser_command, int window_index = 0) -> bool
        RunCommand(self, int browser_command) -> bool

        Like ApplyAccelerator, except that it waits for the command to execute.
        """
        return _pyautolib.PyUITestBase_RunCommand(self, *args)

    def GetDownloadDirectory(self):
        """
        GetDownloadDirectory(self) -> FilePath

        Get the path to download directory.
        """
        return _pyautolib.PyUITestBase_GetDownloadDirectory(self)

    def user_data_dir(self):
        """
        user_data_dir(self) -> FilePath

        Get the path to profile directory.
        """
        return _pyautolib.PyUITestBase_user_data_dir(self)

    def SetDownloadShelfVisible(self, *args):
        """
        SetDownloadShelfVisible(self, bool is_visible, int window_index = 0)
        SetDownloadShelfVisible(self, bool is_visible)

        Set download shelf visibility for the given or first browser window.
        """
        return _pyautolib.PyUITestBase_SetDownloadShelfVisible(self, *args)

    def IsDownloadShelfVisible(self, window_index = 0):
        """
        IsDownloadShelfVisible(self, int window_index = 0) -> bool
        IsDownloadShelfVisible(self) -> bool

        Determine if the download shelf is visible in the given or first browser window.
        """
        return _pyautolib.PyUITestBase_IsDownloadShelfVisible(self, window_index)

    def GetBookmarkBarVisibility(self):
        """
        GetBookmarkBarVisibility(self) -> bool

        Determine if the bookmark bar is visible. If the NTP is visible, only return true if attached (to the chrome).
        """
        return _pyautolib.PyUITestBase_GetBookmarkBarVisibility(self)

    def WaitForBookmarkBarVisibilityChange(self, *args):
        """
        WaitForBookmarkBarVisibilityChange(self, bool wait_for_open) -> bool

        Wait for the bookmark bar animation to complete. |wait_for_open| specifies which kind of change we wait for.
        """
        return _pyautolib.PyUITestBase_WaitForBookmarkBarVisibilityChange(self, *args)

    def _GetBookmarksAsJSON(self):
        """
        _GetBookmarksAsJSON(self) -> string

        Get the bookmarks as a JSON string.  Internal method.
        """
        return _pyautolib.PyUITestBase__GetBookmarksAsJSON(self)

    def AddBookmarkGroup(self, *args):
        """
        AddBookmarkGroup(self, wstring parent_id, int index, wstring title) -> bool

        Add a bookmark folder with the given index in the parent.  |title| is the title/name of the folder.
        """
        return _pyautolib.PyUITestBase_AddBookmarkGroup(self, *args)

    def AddBookmarkURL(self, *args):
        """
        AddBookmarkURL(self, wstring parent_id, int index, wstring title, wstring url) -> bool

        Add a bookmark with the given title and URL.
        """
        return _pyautolib.PyUITestBase_AddBookmarkURL(self, *args)

    def ReparentBookmark(self, *args):
        """
        ReparentBookmark(self, wstring id, wstring new_parent_id, int index) -> bool

        Move a bookmark to a new parent.
        """
        return _pyautolib.PyUITestBase_ReparentBookmark(self, *args)

    def SetBookmarkTitle(self, *args):
        """
        SetBookmarkTitle(self, wstring id, wstring title) -> bool

        Set the title of a bookmark.
        """
        return _pyautolib.PyUITestBase_SetBookmarkTitle(self, *args)

    def SetBookmarkURL(self, *args):
        """
        SetBookmarkURL(self, wstring id, wstring url) -> bool

        Set the URL of a bookmark.
        """
        return _pyautolib.PyUITestBase_SetBookmarkURL(self, *args)

    def RemoveBookmark(self, *args):
        """
        RemoveBookmark(self, wstring id) -> bool

        Remove (delete) a bookmark.
        """
        return _pyautolib.PyUITestBase_RemoveBookmark(self, *args)

    def OpenFindInPage(self, window_index = 0):
        """
        OpenFindInPage(self, int window_index = 0)
        OpenFindInPage(self)

        Open the Find box in the given or first browser window.
        """
        return _pyautolib.PyUITestBase_OpenFindInPage(self, window_index)

    def IsFindInPageVisible(self, window_index = 0):
        """
        IsFindInPageVisible(self, int window_index = 0) -> bool
        IsFindInPageVisible(self) -> bool

        Determine if the find box is visible in the given or first browser window.
        """
        return _pyautolib.PyUITestBase_IsFindInPageVisible(self, window_index)

    def OpenNewBrowserWindow(self, *args):
        """
        OpenNewBrowserWindow(self, bool show) -> bool

        Open a new browser window.
        """
        return _pyautolib.PyUITestBase_OpenNewBrowserWindow(self, *args)

    def CloseBrowserWindow(self, *args):
        """
        CloseBrowserWindow(self, int window_index) -> bool

        Close a browser window.
        """
        return _pyautolib.PyUITestBase_CloseBrowserWindow(self, *args)

    def GetBrowserWindowCount(self):
        """
        GetBrowserWindowCount(self) -> int

        Fetch the number of browser windows. Includes popups.
        """
        return _pyautolib.PyUITestBase_GetBrowserWindowCount(self)

    def GetActiveTabIndex(self, window_index = 0):
        """
        GetActiveTabIndex(self, int window_index = 0) -> int
        GetActiveTabIndex(self) -> int

        Get the index of the active tab in the given or first window. Indexes are zero-based.
        """
        return _pyautolib.PyUITestBase_GetActiveTabIndex(self, window_index)

    def ActivateTab(self, *args):
        """
        ActivateTab(self, int tab_index, int window_index = 0) -> bool
        ActivateTab(self, int tab_index) -> bool

        Activate the tab at the given zero-based index in the given or first window. Returns True on success.
        """
        return _pyautolib.PyUITestBase_ActivateTab(self, *args)

    def GetActiveTabTitle(self, window_index = 0):
        """
        GetActiveTabTitle(self, int window_index = 0) -> wstring
        GetActiveTabTitle(self) -> wstring

        Get the title of the active tab for the given or first window.
        """
        return _pyautolib.PyUITestBase_GetActiveTabTitle(self, window_index)

    def GetActiveTabURL(self, window_index = 0):
        """
        GetActiveTabURL(self, int window_index = 0) -> GURL
        GetActiveTabURL(self) -> GURL

        Get the URL for the active tab. for the given or first window. Returns an instance of GURL
        """
        return _pyautolib.PyUITestBase_GetActiveTabURL(self, window_index)

    def GetTabCount(self, window_index = 0):
        """
        GetTabCount(self, int window_index = 0) -> int
        GetTabCount(self) -> int

        Count of the number of tabs in the given or first window.
        """
        return _pyautolib.PyUITestBase_GetTabCount(self, window_index)

    def AppendTab(self, *args):
        """
        AppendTab(self, GURL tab_url, int window_index = 0) -> bool
        AppendTab(self, GURL tab_url) -> bool

        Create a new tab at the end of given or first browser window and activate it. Blocks until the page is loaded. Returns True on success.
        """
        return _pyautolib.PyUITestBase_AppendTab(self, *args)

    def SetCookie(self, *args):
        """
        SetCookie(self, GURL cookie_url, string value, int window_index = 0, 
            int tab_index = 0) -> bool
        SetCookie(self, GURL cookie_url, string value, int window_index = 0) -> bool
        SetCookie(self, GURL cookie_url, string value) -> bool

        Set the value of the cookie at cookie_url to value for the given window index and tab index. Returns True on success.
        """
        return _pyautolib.PyUITestBase_SetCookie(self, *args)

    def GetCookie(self, *args):
        """
        GetCookie(self, GURL cookie_url, int window_index = 0, int tab_index = 0) -> string
        GetCookie(self, GURL cookie_url, int window_index = 0) -> string
        GetCookie(self, GURL cookie_url) -> string

        Get the value of the cookie at cookie_url for the given window index and tab index. Returns empty string on error or if there is no value for the cookie.
        """
        return _pyautolib.PyUITestBase_GetCookie(self, *args)

    def InstallExtension(self, *args):
        """
        InstallExtension(self, FilePath crx_file, bool with_ui) -> string

        Install an extension from the given file.  The file must be specified with an absolute path. Returns the extension ID if successfully installed and loaded. Otherwise, returns the empty string.
        """
        return _pyautolib.PyUITestBase_InstallExtension(self, *args)

    def GetBrowserWindow(self, *args):
        """
        GetBrowserWindow(self, int window_index) -> scoped_refptr__BrowserProxy

        Get a proxy to the browser window at the given zero-based index.
        """
        return _pyautolib.PyUITestBase_GetBrowserWindow(self, *args)

    def _SendJSONRequest(self, *args):
        """
        _SendJSONRequest(self, int window_index, string request, int timeout) -> string

        Send a sync JSON request to Chrome.  Returns a JSON dict as a response.  Given timeout in milliseconds.Internal method.
        """
        return _pyautolib.PyUITestBase__SendJSONRequest(self, *args)

    def ExecuteJavascript(self, *args):
        """
        ExecuteJavascript(self, wstring script, int window_index = 0, int tab_index = 0, 
            wstring frame_xpath = "") -> wstring
        ExecuteJavascript(self, wstring script, int window_index = 0, int tab_index = 0) -> wstring
        ExecuteJavascript(self, wstring script, int window_index = 0) -> wstring
        ExecuteJavascript(self, wstring script) -> wstring

        Execute a string of javascript in the specified (window, tab, frame) and return a string.
        """
        return _pyautolib.PyUITestBase_ExecuteJavascript(self, *args)

    def GetDOMValue(self, *args):
        """
        GetDOMValue(self, wstring expr, int window_index = 0, int tab_index = 0, 
            wstring frame_xpath = "") -> wstring
        GetDOMValue(self, wstring expr, int window_index = 0, int tab_index = 0) -> wstring
        GetDOMValue(self, wstring expr, int window_index = 0) -> wstring
        GetDOMValue(self, wstring expr) -> wstring

        Evaluate a javascript expression in the specified (window, tab, frame) and return the specified DOM value as a string. This is a wrapper around window.domAutomationController.send().
        """
        return _pyautolib.PyUITestBase_GetDOMValue(self, *args)

    def ResetToDefaultTheme(self):
        """
        ResetToDefaultTheme(self) -> bool

        Resets to the default theme. Returns true on success.
        """
        return _pyautolib.PyUITestBase_ResetToDefaultTheme(self)

    __swig_destroy__ = _pyautolib.delete_PyUITestBase
    __del__ = lambda self : None;
PyUITestBase_swigregister = _pyautolib.PyUITestBase_swigregister
PyUITestBase_swigregister(PyUITestBase)

class TestServer(_object):
    """TestServer. Serves files in data dir over a local http server"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TestServer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TestServer, name)
    __repr__ = _swig_repr
    TYPE_FTP = _pyautolib.TestServer_TYPE_FTP
    TYPE_HTTP = _pyautolib.TestServer_TYPE_HTTP
    TYPE_HTTPS = _pyautolib.TestServer_TYPE_HTTPS
    TYPE_SYNC = _pyautolib.TestServer_TYPE_SYNC
    def __init__(self, *args): 
        """__init__(self, Type type, FilePath document_root) -> TestServer"""
        this = _pyautolib.new_TestServer(*args)
        try: self.this.append(this)
        except: self.this = this
    def Start(self):
        """
        Start(self) -> bool

        Start TestServer over an ephemeral port
        """
        return _pyautolib.TestServer_Start(self)

    def Stop(self):
        """
        Stop(self) -> bool

        Stop TestServer
        """
        return _pyautolib.TestServer_Stop(self)

    def document_root(self):
        """
        document_root(self) -> FilePath

        Get FilePath to the document root
        """
        return _pyautolib.TestServer_document_root(self)

    def GetScheme(self):
        """GetScheme(self) -> string"""
        return _pyautolib.TestServer_GetScheme(self)

    def GetURL(self, *args):
        """
        GetURL(self, string path) -> GURL

        Get URL for a file path
        """
        return _pyautolib.TestServer_GetURL(self, *args)

    __swig_destroy__ = _pyautolib.delete_TestServer
    __del__ = lambda self : None;
TestServer_swigregister = _pyautolib.TestServer_swigregister
TestServer_swigregister(TestServer)



