# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

"""
Python interface to Automation Proxy.
"""

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyautolib', [dirname(__file__)])
        except ImportError:
            import _pyautolib
            return _pyautolib
        if fp is not None:
            try:
                _mod = imp.load_module('_pyautolib', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pyautolib = swig_import_helper()
    del swig_import_helper
else:
    import _pyautolib
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


IDC_MinimumLabelValue = _pyautolib.IDC_MinimumLabelValue
IDC_Messages = _pyautolib.IDC_Messages
IDC_MessagesAll = _pyautolib.IDC_MessagesAll
IDC_MessagesNone = _pyautolib.IDC_MessagesNone
IDC_BACK = _pyautolib.IDC_BACK
IDC_FORWARD = _pyautolib.IDC_FORWARD
IDC_RELOAD = _pyautolib.IDC_RELOAD
IDC_HOME = _pyautolib.IDC_HOME
IDC_OPEN_CURRENT_URL = _pyautolib.IDC_OPEN_CURRENT_URL
IDC_STOP = _pyautolib.IDC_STOP
IDC_RELOAD_IGNORING_CACHE = _pyautolib.IDC_RELOAD_IGNORING_CACHE
IDC_LOAD_NEW_TAB_PAGE = _pyautolib.IDC_LOAD_NEW_TAB_PAGE
IDC_RELOAD_CLEARING_CACHE = _pyautolib.IDC_RELOAD_CLEARING_CACHE
IDC_NEW_WINDOW = _pyautolib.IDC_NEW_WINDOW
IDC_NEW_INCOGNITO_WINDOW = _pyautolib.IDC_NEW_INCOGNITO_WINDOW
IDC_PIN_TO_START_SCREEN = _pyautolib.IDC_PIN_TO_START_SCREEN
IDC_CLOSE_WINDOW = _pyautolib.IDC_CLOSE_WINDOW
IDC_ALWAYS_ON_TOP = _pyautolib.IDC_ALWAYS_ON_TOP
IDC_NEW_TAB = _pyautolib.IDC_NEW_TAB
IDC_CLOSE_TAB = _pyautolib.IDC_CLOSE_TAB
IDC_SELECT_NEXT_TAB = _pyautolib.IDC_SELECT_NEXT_TAB
IDC_SELECT_PREVIOUS_TAB = _pyautolib.IDC_SELECT_PREVIOUS_TAB
IDC_SELECT_TAB_0 = _pyautolib.IDC_SELECT_TAB_0
IDC_SELECT_TAB_1 = _pyautolib.IDC_SELECT_TAB_1
IDC_SELECT_TAB_2 = _pyautolib.IDC_SELECT_TAB_2
IDC_SELECT_TAB_3 = _pyautolib.IDC_SELECT_TAB_3
IDC_SELECT_TAB_4 = _pyautolib.IDC_SELECT_TAB_4
IDC_SELECT_TAB_5 = _pyautolib.IDC_SELECT_TAB_5
IDC_SELECT_TAB_6 = _pyautolib.IDC_SELECT_TAB_6
IDC_SELECT_TAB_7 = _pyautolib.IDC_SELECT_TAB_7
IDC_SELECT_LAST_TAB = _pyautolib.IDC_SELECT_LAST_TAB
IDC_DUPLICATE_TAB = _pyautolib.IDC_DUPLICATE_TAB
IDC_RESTORE_TAB = _pyautolib.IDC_RESTORE_TAB
IDC_SHOW_AS_TAB = _pyautolib.IDC_SHOW_AS_TAB
IDC_FULLSCREEN = _pyautolib.IDC_FULLSCREEN
IDC_EXIT = _pyautolib.IDC_EXIT
IDC_MOVE_TAB_NEXT = _pyautolib.IDC_MOVE_TAB_NEXT
IDC_MOVE_TAB_PREVIOUS = _pyautolib.IDC_MOVE_TAB_PREVIOUS
IDC_SEARCH = _pyautolib.IDC_SEARCH
IDC_TABPOSE = _pyautolib.IDC_TABPOSE
IDC_DEBUG_FRAME_TOGGLE = _pyautolib.IDC_DEBUG_FRAME_TOGGLE
IDC_PRESENTATION_MODE = _pyautolib.IDC_PRESENTATION_MODE
IDC_METRO_SNAP_ENABLE = _pyautolib.IDC_METRO_SNAP_ENABLE
IDC_METRO_SNAP_DISABLE = _pyautolib.IDC_METRO_SNAP_DISABLE
IDC_WIN8_DESKTOP_RESTART = _pyautolib.IDC_WIN8_DESKTOP_RESTART
IDC_WIN8_METRO_RESTART = _pyautolib.IDC_WIN8_METRO_RESTART
IDC_TOGGLE_ASH_DESKTOP = _pyautolib.IDC_TOGGLE_ASH_DESKTOP
IDC_BOOKMARK_PAGE = _pyautolib.IDC_BOOKMARK_PAGE
IDC_BOOKMARK_ALL_TABS = _pyautolib.IDC_BOOKMARK_ALL_TABS
IDC_VIEW_SOURCE = _pyautolib.IDC_VIEW_SOURCE
IDC_PRINT = _pyautolib.IDC_PRINT
IDC_SAVE_PAGE = _pyautolib.IDC_SAVE_PAGE
IDC_ENCODING_MENU = _pyautolib.IDC_ENCODING_MENU
IDC_EMAIL_PAGE_LOCATION = _pyautolib.IDC_EMAIL_PAGE_LOCATION
IDC_ADVANCED_PRINT = _pyautolib.IDC_ADVANCED_PRINT
IDC_CHROME_TO_MOBILE_PAGE = _pyautolib.IDC_CHROME_TO_MOBILE_PAGE
IDC_PRINT_TO_DESTINATION = _pyautolib.IDC_PRINT_TO_DESTINATION
IDC_BOOKMARK_PAGE_FROM_STAR = _pyautolib.IDC_BOOKMARK_PAGE_FROM_STAR
IDC_ENCODING_AUTO_DETECT = _pyautolib.IDC_ENCODING_AUTO_DETECT
IDC_ENCODING_UTF8 = _pyautolib.IDC_ENCODING_UTF8
IDC_ENCODING_UTF16LE = _pyautolib.IDC_ENCODING_UTF16LE
IDC_ENCODING_ISO88591 = _pyautolib.IDC_ENCODING_ISO88591
IDC_ENCODING_WINDOWS1252 = _pyautolib.IDC_ENCODING_WINDOWS1252
IDC_ENCODING_GBK = _pyautolib.IDC_ENCODING_GBK
IDC_ENCODING_GB18030 = _pyautolib.IDC_ENCODING_GB18030
IDC_ENCODING_BIG5 = _pyautolib.IDC_ENCODING_BIG5
IDC_ENCODING_BIG5HKSCS = _pyautolib.IDC_ENCODING_BIG5HKSCS
IDC_ENCODING_KOREAN = _pyautolib.IDC_ENCODING_KOREAN
IDC_ENCODING_SHIFTJIS = _pyautolib.IDC_ENCODING_SHIFTJIS
IDC_ENCODING_ISO2022JP = _pyautolib.IDC_ENCODING_ISO2022JP
IDC_ENCODING_EUCJP = _pyautolib.IDC_ENCODING_EUCJP
IDC_ENCODING_THAI = _pyautolib.IDC_ENCODING_THAI
IDC_ENCODING_ISO885915 = _pyautolib.IDC_ENCODING_ISO885915
IDC_ENCODING_MACINTOSH = _pyautolib.IDC_ENCODING_MACINTOSH
IDC_ENCODING_ISO88592 = _pyautolib.IDC_ENCODING_ISO88592
IDC_ENCODING_WINDOWS1250 = _pyautolib.IDC_ENCODING_WINDOWS1250
IDC_ENCODING_ISO88595 = _pyautolib.IDC_ENCODING_ISO88595
IDC_ENCODING_WINDOWS1251 = _pyautolib.IDC_ENCODING_WINDOWS1251
IDC_ENCODING_KOI8R = _pyautolib.IDC_ENCODING_KOI8R
IDC_ENCODING_KOI8U = _pyautolib.IDC_ENCODING_KOI8U
IDC_ENCODING_ISO88597 = _pyautolib.IDC_ENCODING_ISO88597
IDC_ENCODING_WINDOWS1253 = _pyautolib.IDC_ENCODING_WINDOWS1253
IDC_ENCODING_ISO88594 = _pyautolib.IDC_ENCODING_ISO88594
IDC_ENCODING_ISO885913 = _pyautolib.IDC_ENCODING_ISO885913
IDC_ENCODING_WINDOWS1257 = _pyautolib.IDC_ENCODING_WINDOWS1257
IDC_ENCODING_ISO88593 = _pyautolib.IDC_ENCODING_ISO88593
IDC_ENCODING_ISO885910 = _pyautolib.IDC_ENCODING_ISO885910
IDC_ENCODING_ISO885914 = _pyautolib.IDC_ENCODING_ISO885914
IDC_ENCODING_ISO885916 = _pyautolib.IDC_ENCODING_ISO885916
IDC_ENCODING_WINDOWS1254 = _pyautolib.IDC_ENCODING_WINDOWS1254
IDC_ENCODING_ISO88596 = _pyautolib.IDC_ENCODING_ISO88596
IDC_ENCODING_WINDOWS1256 = _pyautolib.IDC_ENCODING_WINDOWS1256
IDC_ENCODING_ISO88598 = _pyautolib.IDC_ENCODING_ISO88598
IDC_ENCODING_WINDOWS1255 = _pyautolib.IDC_ENCODING_WINDOWS1255
IDC_ENCODING_WINDOWS1258 = _pyautolib.IDC_ENCODING_WINDOWS1258
IDC_ENCODING_ISO88598I = _pyautolib.IDC_ENCODING_ISO88598I
IDC_CUT = _pyautolib.IDC_CUT
IDC_COPY = _pyautolib.IDC_COPY
IDC_COPY_URL = _pyautolib.IDC_COPY_URL
IDC_PASTE = _pyautolib.IDC_PASTE
IDC_EDIT_MENU = _pyautolib.IDC_EDIT_MENU
IDC_FIND = _pyautolib.IDC_FIND
IDC_FIND_NEXT = _pyautolib.IDC_FIND_NEXT
IDC_FIND_PREVIOUS = _pyautolib.IDC_FIND_PREVIOUS
IDC_ZOOM_MENU = _pyautolib.IDC_ZOOM_MENU
IDC_ZOOM_PLUS = _pyautolib.IDC_ZOOM_PLUS
IDC_ZOOM_NORMAL = _pyautolib.IDC_ZOOM_NORMAL
IDC_ZOOM_MINUS = _pyautolib.IDC_ZOOM_MINUS
IDC_ZOOM_PERCENT_DISPLAY = _pyautolib.IDC_ZOOM_PERCENT_DISPLAY
IDC_FOCUS_TOOLBAR = _pyautolib.IDC_FOCUS_TOOLBAR
IDC_FOCUS_LOCATION = _pyautolib.IDC_FOCUS_LOCATION
IDC_FOCUS_SEARCH = _pyautolib.IDC_FOCUS_SEARCH
IDC_FOCUS_MENU_BAR = _pyautolib.IDC_FOCUS_MENU_BAR
IDC_FOCUS_NEXT_PANE = _pyautolib.IDC_FOCUS_NEXT_PANE
IDC_FOCUS_PREVIOUS_PANE = _pyautolib.IDC_FOCUS_PREVIOUS_PANE
IDC_FOCUS_BOOKMARKS = _pyautolib.IDC_FOCUS_BOOKMARKS
IDC_OPEN_FILE = _pyautolib.IDC_OPEN_FILE
IDC_CREATE_SHORTCUTS = _pyautolib.IDC_CREATE_SHORTCUTS
IDC_DEVELOPER_MENU = _pyautolib.IDC_DEVELOPER_MENU
IDC_DEV_TOOLS = _pyautolib.IDC_DEV_TOOLS
IDC_DEV_TOOLS_CONSOLE = _pyautolib.IDC_DEV_TOOLS_CONSOLE
IDC_TASK_MANAGER = _pyautolib.IDC_TASK_MANAGER
IDC_FEEDBACK = _pyautolib.IDC_FEEDBACK
IDC_SHOW_BOOKMARK_BAR = _pyautolib.IDC_SHOW_BOOKMARK_BAR
IDC_SHOW_HISTORY = _pyautolib.IDC_SHOW_HISTORY
IDC_SHOW_BOOKMARK_MANAGER = _pyautolib.IDC_SHOW_BOOKMARK_MANAGER
IDC_SHOW_DOWNLOADS = _pyautolib.IDC_SHOW_DOWNLOADS
IDC_CLEAR_BROWSING_DATA = _pyautolib.IDC_CLEAR_BROWSING_DATA
IDC_IMPORT_SETTINGS = _pyautolib.IDC_IMPORT_SETTINGS
IDC_OPTIONS = _pyautolib.IDC_OPTIONS
IDC_EDIT_SEARCH_ENGINES = _pyautolib.IDC_EDIT_SEARCH_ENGINES
IDC_VIEW_PASSWORDS = _pyautolib.IDC_VIEW_PASSWORDS
IDC_ABOUT = _pyautolib.IDC_ABOUT
IDC_HELP_PAGE_VIA_KEYBOARD = _pyautolib.IDC_HELP_PAGE_VIA_KEYBOARD
IDC_HELP_PAGE_VIA_MENU = _pyautolib.IDC_HELP_PAGE_VIA_MENU
IDC_SHOW_APP_MENU = _pyautolib.IDC_SHOW_APP_MENU
IDC_MANAGE_EXTENSIONS = _pyautolib.IDC_MANAGE_EXTENSIONS
IDC_DEV_TOOLS_INSPECT = _pyautolib.IDC_DEV_TOOLS_INSPECT
IDC_UPGRADE_DIALOG = _pyautolib.IDC_UPGRADE_DIALOG
IDC_VIEW_INCOMPATIBILITIES = _pyautolib.IDC_VIEW_INCOMPATIBILITIES
IDC_VIEW_BACKGROUND_PAGES = _pyautolib.IDC_VIEW_BACKGROUND_PAGES
IDC_SHOW_KEYBOARD_OVERLAY = _pyautolib.IDC_SHOW_KEYBOARD_OVERLAY
IDC_PROFILING_ENABLED = _pyautolib.IDC_PROFILING_ENABLED
IDC_BOOKMARKS_MENU = _pyautolib.IDC_BOOKMARKS_MENU
IDC_SHOW_SYNC_SETUP = _pyautolib.IDC_SHOW_SYNC_SETUP
IDC_EXTENSION_ERRORS = _pyautolib.IDC_EXTENSION_ERRORS
IDC_SHOW_SYNC_ERROR = _pyautolib.IDC_SHOW_SYNC_ERROR
IDC_SHOW_SETTINGS_CHANGE_FIRST = _pyautolib.IDC_SHOW_SETTINGS_CHANGE_FIRST
IDC_SHOW_SETTINGS_CHANGE_LAST = _pyautolib.IDC_SHOW_SETTINGS_CHANGE_LAST
IDC_SHOW_AVATAR_MENU = _pyautolib.IDC_SHOW_AVATAR_MENU
IDC_EXTENSION_DISABLED_FIRST = _pyautolib.IDC_EXTENSION_DISABLED_FIRST
IDC_EXTENSION_DISABLED_LAST = _pyautolib.IDC_EXTENSION_DISABLED_LAST
IDC_TOGGLE_REQUEST_TABLET_SITE = _pyautolib.IDC_TOGGLE_REQUEST_TABLET_SITE
IDC_DEV_TOOLS_TOGGLE = _pyautolib.IDC_DEV_TOOLS_TOGGLE
IDC_EXTERNAL_EXTENSION_ALERT = _pyautolib.IDC_EXTERNAL_EXTENSION_ALERT
IDC_RECENT_TABS_MENU = _pyautolib.IDC_RECENT_TABS_MENU
IDC_RECENT_TABS_NO_DEVICE_TABS = _pyautolib.IDC_RECENT_TABS_NO_DEVICE_TABS
IDC_SPELLCHECK_SUGGESTION_0 = _pyautolib.IDC_SPELLCHECK_SUGGESTION_0
IDC_SPELLCHECK_SUGGESTION_1 = _pyautolib.IDC_SPELLCHECK_SUGGESTION_1
IDC_SPELLCHECK_SUGGESTION_2 = _pyautolib.IDC_SPELLCHECK_SUGGESTION_2
IDC_SPELLCHECK_SUGGESTION_3 = _pyautolib.IDC_SPELLCHECK_SUGGESTION_3
IDC_SPELLCHECK_SUGGESTION_4 = _pyautolib.IDC_SPELLCHECK_SUGGESTION_4
IDC_SPELLCHECK_SUGGESTION_LAST = _pyautolib.IDC_SPELLCHECK_SUGGESTION_LAST
IDC_SPELLCHECK_MENU = _pyautolib.IDC_SPELLCHECK_MENU
IDC_SPELLCHECK_LANGUAGES_FIRST = _pyautolib.IDC_SPELLCHECK_LANGUAGES_FIRST
IDC_SPELLCHECK_LANGUAGES_LAST = _pyautolib.IDC_SPELLCHECK_LANGUAGES_LAST
IDC_CHECK_SPELLING_WHILE_TYPING = _pyautolib.IDC_CHECK_SPELLING_WHILE_TYPING
IDC_SPELLPANEL_TOGGLE = _pyautolib.IDC_SPELLPANEL_TOGGLE
IDC_SPELLCHECK_ADD_TO_DICTIONARY = _pyautolib.IDC_SPELLCHECK_ADD_TO_DICTIONARY
IDC_WRITING_DIRECTION_MENU = _pyautolib.IDC_WRITING_DIRECTION_MENU
IDC_WRITING_DIRECTION_DEFAULT = _pyautolib.IDC_WRITING_DIRECTION_DEFAULT
IDC_WRITING_DIRECTION_LTR = _pyautolib.IDC_WRITING_DIRECTION_LTR
IDC_WRITING_DIRECTION_RTL = _pyautolib.IDC_WRITING_DIRECTION_RTL
IDC_TRANSLATE_OPTIONS_ALWAYS = _pyautolib.IDC_TRANSLATE_OPTIONS_ALWAYS
IDC_TRANSLATE_OPTIONS_NEVER_TRANSLATE_LANG = _pyautolib.IDC_TRANSLATE_OPTIONS_NEVER_TRANSLATE_LANG
IDC_TRANSLATE_OPTIONS_NEVER_TRANSLATE_SITE = _pyautolib.IDC_TRANSLATE_OPTIONS_NEVER_TRANSLATE_SITE
IDC_TRANSLATE_REPORT_BAD_LANGUAGE_DETECTION = _pyautolib.IDC_TRANSLATE_REPORT_BAD_LANGUAGE_DETECTION
IDC_TRANSLATE_OPTIONS_ABOUT = _pyautolib.IDC_TRANSLATE_OPTIONS_ABOUT
IDC_TRANSLATE_ORIGINAL_LANGUAGE_BASE = _pyautolib.IDC_TRANSLATE_ORIGINAL_LANGUAGE_BASE
IDC_TRANSLATE_TARGET_LANGUAGE_BASE = _pyautolib.IDC_TRANSLATE_TARGET_LANGUAGE_BASE
IDC_TOGGLE_SPEECH_INPUT = _pyautolib.IDC_TOGGLE_SPEECH_INPUT
IDC_VIEW_MENU = _pyautolib.IDC_VIEW_MENU
IDC_HISTORY_MENU = _pyautolib.IDC_HISTORY_MENU
IDC_PROFILE_MAIN_MENU = _pyautolib.IDC_PROFILE_MAIN_MENU
IDC_INPUT_METHODS_MENU = _pyautolib.IDC_INPUT_METHODS_MENU
IDC_CONTENT_CONTEXT_CUSTOM_FIRST = _pyautolib.IDC_CONTENT_CONTEXT_CUSTOM_FIRST
IDC_CONTENT_CONTEXT_CUSTOM_LAST = _pyautolib.IDC_CONTENT_CONTEXT_CUSTOM_LAST
IDC_EXTENSIONS_CONTEXT_CUSTOM_FIRST = _pyautolib.IDC_EXTENSIONS_CONTEXT_CUSTOM_FIRST
IDC_EXTENSIONS_CONTEXT_CUSTOM_LAST = _pyautolib.IDC_EXTENSIONS_CONTEXT_CUSTOM_LAST
IDC_CONTENT_CONTEXT_OPENLINKNEWTAB = _pyautolib.IDC_CONTENT_CONTEXT_OPENLINKNEWTAB
IDC_CONTENT_CONTEXT_OPENLINKNEWWINDOW = _pyautolib.IDC_CONTENT_CONTEXT_OPENLINKNEWWINDOW
IDC_CONTENT_CONTEXT_OPENLINKOFFTHERECORD = _pyautolib.IDC_CONTENT_CONTEXT_OPENLINKOFFTHERECORD
IDC_CONTENT_CONTEXT_SAVELINKAS = _pyautolib.IDC_CONTENT_CONTEXT_SAVELINKAS
IDC_CONTENT_CONTEXT_COPYLINKLOCATION = _pyautolib.IDC_CONTENT_CONTEXT_COPYLINKLOCATION
IDC_CONTENT_CONTEXT_COPYEMAILADDRESS = _pyautolib.IDC_CONTENT_CONTEXT_COPYEMAILADDRESS
IDC_CONTENT_CONTEXT_OPENLINKWITH = _pyautolib.IDC_CONTENT_CONTEXT_OPENLINKWITH
IDC_CONTENT_CONTEXT_SAVEIMAGEAS = _pyautolib.IDC_CONTENT_CONTEXT_SAVEIMAGEAS
IDC_CONTENT_CONTEXT_COPYIMAGELOCATION = _pyautolib.IDC_CONTENT_CONTEXT_COPYIMAGELOCATION
IDC_CONTENT_CONTEXT_COPYIMAGE = _pyautolib.IDC_CONTENT_CONTEXT_COPYIMAGE
IDC_CONTENT_CONTEXT_OPENIMAGENEWTAB = _pyautolib.IDC_CONTENT_CONTEXT_OPENIMAGENEWTAB
IDC_CONTENT_CONTEXT_SAVEAVAS = _pyautolib.IDC_CONTENT_CONTEXT_SAVEAVAS
IDC_CONTENT_CONTEXT_COPYAVLOCATION = _pyautolib.IDC_CONTENT_CONTEXT_COPYAVLOCATION
IDC_CONTENT_CONTEXT_OPENAVNEWTAB = _pyautolib.IDC_CONTENT_CONTEXT_OPENAVNEWTAB
IDC_CONTENT_CONTEXT_PLAYPAUSE = _pyautolib.IDC_CONTENT_CONTEXT_PLAYPAUSE
IDC_CONTENT_CONTEXT_MUTE = _pyautolib.IDC_CONTENT_CONTEXT_MUTE
IDC_CONTENT_CONTEXT_LOOP = _pyautolib.IDC_CONTENT_CONTEXT_LOOP
IDC_CONTENT_CONTEXT_CONTROLS = _pyautolib.IDC_CONTENT_CONTEXT_CONTROLS
IDC_CONTENT_CONTEXT_ROTATECW = _pyautolib.IDC_CONTENT_CONTEXT_ROTATECW
IDC_CONTENT_CONTEXT_ROTATECCW = _pyautolib.IDC_CONTENT_CONTEXT_ROTATECCW
IDC_CONTENT_CONTEXT_COPY = _pyautolib.IDC_CONTENT_CONTEXT_COPY
IDC_CONTENT_CONTEXT_CUT = _pyautolib.IDC_CONTENT_CONTEXT_CUT
IDC_CONTENT_CONTEXT_PASTE = _pyautolib.IDC_CONTENT_CONTEXT_PASTE
IDC_CONTENT_CONTEXT_DELETE = _pyautolib.IDC_CONTENT_CONTEXT_DELETE
IDC_CONTENT_CONTEXT_UNDO = _pyautolib.IDC_CONTENT_CONTEXT_UNDO
IDC_CONTENT_CONTEXT_REDO = _pyautolib.IDC_CONTENT_CONTEXT_REDO
IDC_CONTENT_CONTEXT_SELECTALL = _pyautolib.IDC_CONTENT_CONTEXT_SELECTALL
IDC_CONTENT_CONTEXT_PASTE_AND_MATCH_STYLE = _pyautolib.IDC_CONTENT_CONTEXT_PASTE_AND_MATCH_STYLE
IDC_CONTENT_CONTEXT_TRANSLATE = _pyautolib.IDC_CONTENT_CONTEXT_TRANSLATE
IDC_CONTENT_CONTEXT_INSPECTELEMENT = _pyautolib.IDC_CONTENT_CONTEXT_INSPECTELEMENT
IDC_CONTENT_CONTEXT_VIEWPAGEINFO = _pyautolib.IDC_CONTENT_CONTEXT_VIEWPAGEINFO
IDC_CONTENT_CONTEXT_LANGUAGE_SETTINGS = _pyautolib.IDC_CONTENT_CONTEXT_LANGUAGE_SETTINGS
IDC_CONTENT_CONTEXT_LOOK_UP_IN_DICTIONARY = _pyautolib.IDC_CONTENT_CONTEXT_LOOK_UP_IN_DICTIONARY
IDC_CONTENT_CONTEXT_NO_SPELLING_SUGGESTIONS = _pyautolib.IDC_CONTENT_CONTEXT_NO_SPELLING_SUGGESTIONS
IDC_CONTENT_CONTEXT_SPELLING_SUGGESTION = _pyautolib.IDC_CONTENT_CONTEXT_SPELLING_SUGGESTION
IDC_CONTENT_CONTEXT_SPELLING_TOGGLE = _pyautolib.IDC_CONTENT_CONTEXT_SPELLING_TOGGLE
IDC_CONTENT_CONTEXT_SPEECH_MENU = _pyautolib.IDC_CONTENT_CONTEXT_SPEECH_MENU
IDC_CONTENT_CONTEXT_SPEECH_START_SPEAKING = _pyautolib.IDC_CONTENT_CONTEXT_SPEECH_START_SPEAKING
IDC_CONTENT_CONTEXT_SPEECH_STOP_SPEAKING = _pyautolib.IDC_CONTENT_CONTEXT_SPEECH_STOP_SPEAKING
IDC_CONTENT_CONTEXT_INSPECTBACKGROUNDPAGE = _pyautolib.IDC_CONTENT_CONTEXT_INSPECTBACKGROUNDPAGE
IDC_CONTENT_CONTEXT_RELOAD_PACKAGED_APP = _pyautolib.IDC_CONTENT_CONTEXT_RELOAD_PACKAGED_APP
IDC_CONTENT_CONTEXT_RESTART_PACKAGED_APP = _pyautolib.IDC_CONTENT_CONTEXT_RESTART_PACKAGED_APP
IDC_CONTENT_CONTEXT_AUTOCORRECT_SPELLING_TOGGLE = _pyautolib.IDC_CONTENT_CONTEXT_AUTOCORRECT_SPELLING_TOGGLE
IDC_CONTENT_CONTEXT_RELOADFRAME = _pyautolib.IDC_CONTENT_CONTEXT_RELOADFRAME
IDC_CONTENT_CONTEXT_VIEWFRAMESOURCE = _pyautolib.IDC_CONTENT_CONTEXT_VIEWFRAMESOURCE
IDC_CONTENT_CONTEXT_VIEWFRAMEINFO = _pyautolib.IDC_CONTENT_CONTEXT_VIEWFRAMEINFO
IDC_CONTENT_CONTEXT_GOTOURL = _pyautolib.IDC_CONTENT_CONTEXT_GOTOURL
IDC_CONTENT_CONTEXT_SEARCHWEBFOR = _pyautolib.IDC_CONTENT_CONTEXT_SEARCHWEBFOR
IDC_CONTENT_CONTEXT_ADDSEARCHENGINE = _pyautolib.IDC_CONTENT_CONTEXT_ADDSEARCHENGINE
IDC_BOOKMARK_BAR_OPEN_ALL = _pyautolib.IDC_BOOKMARK_BAR_OPEN_ALL
IDC_BOOKMARK_BAR_OPEN_ALL_NEW_WINDOW = _pyautolib.IDC_BOOKMARK_BAR_OPEN_ALL_NEW_WINDOW
IDC_BOOKMARK_BAR_OPEN_ALL_INCOGNITO = _pyautolib.IDC_BOOKMARK_BAR_OPEN_ALL_INCOGNITO
IDC_BOOKMARK_BAR_OPEN_INCOGNITO = _pyautolib.IDC_BOOKMARK_BAR_OPEN_INCOGNITO
IDC_BOOKMARK_BAR_RENAME_FOLDER = _pyautolib.IDC_BOOKMARK_BAR_RENAME_FOLDER
IDC_BOOKMARK_BAR_EDIT = _pyautolib.IDC_BOOKMARK_BAR_EDIT
IDC_BOOKMARK_BAR_REMOVE = _pyautolib.IDC_BOOKMARK_BAR_REMOVE
IDC_BOOKMARK_BAR_ADD_NEW_BOOKMARK = _pyautolib.IDC_BOOKMARK_BAR_ADD_NEW_BOOKMARK
IDC_BOOKMARK_BAR_NEW_FOLDER = _pyautolib.IDC_BOOKMARK_BAR_NEW_FOLDER
IDC_BOOKMARK_MANAGER = _pyautolib.IDC_BOOKMARK_MANAGER
IDC_BOOKMARK_BAR_ALWAYS_SHOW = _pyautolib.IDC_BOOKMARK_BAR_ALWAYS_SHOW
IDC_STATUS_TRAY_KEEP_CHROME_RUNNING_IN_BACKGROUND = _pyautolib.IDC_STATUS_TRAY_KEEP_CHROME_RUNNING_IN_BACKGROUND
IDC_SPEECH_INPUT_MENU = _pyautolib.IDC_SPEECH_INPUT_MENU
IDC_CONTENT_CONTEXT_SPEECH_INPUT_FILTER_PROFANITIES = _pyautolib.IDC_CONTENT_CONTEXT_SPEECH_INPUT_FILTER_PROFANITIES
IDC_CONTENT_CONTEXT_SPEECH_INPUT_ABOUT = _pyautolib.IDC_CONTENT_CONTEXT_SPEECH_INPUT_ABOUT
IDC_MEDIA_STREAM_DEVICE_STATUS_TRAY = _pyautolib.IDC_MEDIA_STREAM_DEVICE_STATUS_TRAY
IDC_MEDIA_CONTEXT_MEDIA_STREAM_CAPTURE_LIST_FIRST = _pyautolib.IDC_MEDIA_CONTEXT_MEDIA_STREAM_CAPTURE_LIST_FIRST
IDC_MEDIA_CONTEXT_MEDIA_STREAM_CAPTURE_LIST_LAST = _pyautolib.IDC_MEDIA_CONTEXT_MEDIA_STREAM_CAPTURE_LIST_LAST
IDC_MEDIA_STREAM_DEVICE_ALWAYS_ALLOW = _pyautolib.IDC_MEDIA_STREAM_DEVICE_ALWAYS_ALLOW
IDC_CONTENT_CONTEXT_PROTOCOL_HANDLER_FIRST = _pyautolib.IDC_CONTENT_CONTEXT_PROTOCOL_HANDLER_FIRST
IDC_CONTENT_CONTEXT_PROTOCOL_HANDLER_LAST = _pyautolib.IDC_CONTENT_CONTEXT_PROTOCOL_HANDLER_LAST
IDC_CONTENT_CONTEXT_PROTOCOL_HANDLER_SETTINGS = _pyautolib.IDC_CONTENT_CONTEXT_PROTOCOL_HANDLER_SETTINGS
IDR_MAINFRAME = _pyautolib.IDR_MAINFRAME
IDR_CHROMEFRAME = _pyautolib.IDR_CHROMEFRAME
IDI_THROBBER_01 = _pyautolib.IDI_THROBBER_01
IDI_THROBBER_02 = _pyautolib.IDI_THROBBER_02
IDI_THROBBER_03 = _pyautolib.IDI_THROBBER_03
IDI_THROBBER_04 = _pyautolib.IDI_THROBBER_04
IDI_THROBBER_05 = _pyautolib.IDI_THROBBER_05
IDI_THROBBER_06 = _pyautolib.IDI_THROBBER_06
IDI_THROBBER_07 = _pyautolib.IDI_THROBBER_07
IDI_THROBBER_08 = _pyautolib.IDI_THROBBER_08
IDI_THROBBER_09 = _pyautolib.IDI_THROBBER_09
IDI_THROBBER_10 = _pyautolib.IDI_THROBBER_10
IDI_THROBBER_11 = _pyautolib.IDI_THROBBER_11
IDI_THROBBER_12 = _pyautolib.IDI_THROBBER_12
IDI_THROBBER_13 = _pyautolib.IDI_THROBBER_13
IDI_THROBBER_14 = _pyautolib.IDI_THROBBER_14
IDI_THROBBER_15 = _pyautolib.IDI_THROBBER_15
IDI_THROBBER_16 = _pyautolib.IDI_THROBBER_16
IDI_THROBBER_17 = _pyautolib.IDI_THROBBER_17
IDI_THROBBER_18 = _pyautolib.IDI_THROBBER_18
IDI_THROBBER_19 = _pyautolib.IDI_THROBBER_19
IDI_THROBBER_20 = _pyautolib.IDI_THROBBER_20
IDI_THROBBER_21 = _pyautolib.IDI_THROBBER_21
IDI_THROBBER_22 = _pyautolib.IDI_THROBBER_22
IDI_THROBBER_23 = _pyautolib.IDI_THROBBER_23
IDI_THROBBER_24 = _pyautolib.IDI_THROBBER_24
IDR_SXS = _pyautolib.IDR_SXS
IDD_IPC_SETTINGS = _pyautolib.IDD_IPC_SETTINGS
kRawKeyDownType = _pyautolib.kRawKeyDownType
kKeyDownType = _pyautolib.kKeyDownType
kCharType = _pyautolib.kCharType
kKeyUpType = _pyautolib.kKeyUpType
kShiftKeyMask = _pyautolib.kShiftKeyMask
kControlKeyMask = _pyautolib.kControlKeyMask
kAltKeyMask = _pyautolib.kAltKeyMask
kMetaKeyMask = _pyautolib.kMetaKeyMask
kNumLockKeyMask = _pyautolib.kNumLockKeyMask
kMouseDown = _pyautolib.kMouseDown
kMouseUp = _pyautolib.kMouseUp
kMouseMove = _pyautolib.kMouseMove
kMouseEnter = _pyautolib.kMouseEnter
kMouseLeave = _pyautolib.kMouseLeave
kContextMenu = _pyautolib.kContextMenu
kLeftButton = _pyautolib.kLeftButton
kMiddleButton = _pyautolib.kMiddleButton
kRightButton = _pyautolib.kRightButton
kNoButton = _pyautolib.kNoButton
kUnknownError = _pyautolib.kUnknownError
kNoJavaScriptModalDialogOpen = _pyautolib.kNoJavaScriptModalDialogOpen
kBlockedByModalDialog = _pyautolib.kBlockedByModalDialog
kInvalidId = _pyautolib.kInvalidId
class Error(_object):
    """Proxy of C++ automation::Error class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Error, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Error, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> Error
        __init__(self, ErrorCode code) -> Error
        __init__(self, string error_msg) -> Error
        __init__(self, ErrorCode code, string error_msg) -> Error
        """
        this = _pyautolib.new_Error(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pyautolib.delete_Error
    __del__ = lambda self : None;
    def code(self):
        """code(self) -> ErrorCode"""
        return _pyautolib.Error_code(self)

    def message(self):
        """message(self) -> string"""
        return _pyautolib.Error_message(self)

Error_swigregister = _pyautolib.Error_swigregister
Error_swigregister(Error)
cvar = _pyautolib.cvar
kJSONProxyAutoconfig = cvar.kJSONProxyAutoconfig
kJSONProxyNoProxy = cvar.kJSONProxyNoProxy
kJSONProxyPacUrl = cvar.kJSONProxyPacUrl
kJSONProxyPacMandatory = cvar.kJSONProxyPacMandatory
kJSONProxyBypassList = cvar.kJSONProxyBypassList
kJSONProxyServer = cvar.kJSONProxyServer
kNamedInterfacePrefix = cvar.kNamedInterfacePrefix
kSleepTime = cvar.kSleepTime
kChromeDriverAutomationVersion = cvar.kChromeDriverAutomationVersion

AUTOMATION_LAUNCH_RESULT_INVALID = _pyautolib.AUTOMATION_LAUNCH_RESULT_INVALID
AUTOMATION_SUCCESS = _pyautolib.AUTOMATION_SUCCESS
AUTOMATION_TIMEOUT = _pyautolib.AUTOMATION_TIMEOUT
AUTOMATION_VERSION_MISMATCH = _pyautolib.AUTOMATION_VERSION_MISMATCH
AUTOMATION_CREATE_TAB_FAILED = _pyautolib.AUTOMATION_CREATE_TAB_FAILED
AUTOMATION_SERVER_CRASHED = _pyautolib.AUTOMATION_SERVER_CRASHED
AUTOMATION_CHANNEL_ERROR = _pyautolib.AUTOMATION_CHANNEL_ERROR
AUTOMATION_MSG_NAVIGATION_ERROR = _pyautolib.AUTOMATION_MSG_NAVIGATION_ERROR
AUTOMATION_MSG_NAVIGATION_SUCCESS = _pyautolib.AUTOMATION_MSG_NAVIGATION_SUCCESS
AUTOMATION_MSG_NAVIGATION_AUTH_NEEDED = _pyautolib.AUTOMATION_MSG_NAVIGATION_AUTH_NEEDED
AUTOMATION_MSG_NAVIGATION_BLOCKED_BY_MODAL_DIALOG = _pyautolib.AUTOMATION_MSG_NAVIGATION_BLOCKED_BY_MODAL_DIALOG
AUTOMATION_MSG_EXTENSION_ID = _pyautolib.AUTOMATION_MSG_EXTENSION_ID
AUTOMATION_MSG_EXTENSION_NAME = _pyautolib.AUTOMATION_MSG_EXTENSION_NAME
AUTOMATION_MSG_EXTENSION_VERSION = _pyautolib.AUTOMATION_MSG_EXTENSION_VERSION
AUTOMATION_MSG_EXTENSION_BROWSER_ACTION_INDEX = _pyautolib.AUTOMATION_MSG_EXTENSION_BROWSER_ACTION_INDEX
SMALLEST_FONT = _pyautolib.SMALLEST_FONT
SMALL_FONT = _pyautolib.SMALL_FONT
MEDIUM_FONT = _pyautolib.MEDIUM_FONT
LARGE_FONT = _pyautolib.LARGE_FONT
LARGEST_FONT = _pyautolib.LARGEST_FONT
BACK = _pyautolib.BACK
FWD = _pyautolib.FWD
IGNORE_CASE = _pyautolib.IGNORE_CASE
CASE_SENSITIVE = _pyautolib.CASE_SENSITIVE
PAGE_TYPE_NORMAL = _pyautolib.PAGE_TYPE_NORMAL
PAGE_TYPE_ERROR = _pyautolib.PAGE_TYPE_ERROR
PAGE_TYPE_INTERSTITIAL = _pyautolib.PAGE_TYPE_INTERSTITIAL
SECURITY_STYLE_UNKNOWN = _pyautolib.SECURITY_STYLE_UNKNOWN
SECURITY_STYLE_UNAUTHENTICATED = _pyautolib.SECURITY_STYLE_UNAUTHENTICATED
SECURITY_STYLE_AUTHENTICATION_BROKEN = _pyautolib.SECURITY_STYLE_AUTHENTICATION_BROKEN
SECURITY_STYLE_AUTHENTICATED = _pyautolib.SECURITY_STYLE_AUTHENTICATED

def IsCertStatusError(*args):
  """IsCertStatusError(CertStatus status) -> bool"""
  return _pyautolib.IsCertStatusError(*args)

def IsCertStatusMinorError(*args):
  """IsCertStatusMinorError(CertStatus cert_status) -> bool"""
  return _pyautolib.IsCertStatusMinorError(*args)

def MapCertStatusToNetError(*args):
  """MapCertStatusToNetError(CertStatus cert_status) -> int"""
  return _pyautolib.MapCertStatusToNetError(*args)
class GURL(_object):
    """Represent a URL. Call spec() to get the string."""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GURL, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GURL, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> GURL
        __init__(self, string url_string) -> GURL

        Represent a URL. Call spec() to get the string.
        """
        this = _pyautolib.new_GURL(*args)
        try: self.this.append(this)
        except: self.this = this
    def spec(self):
        """
        spec(self) -> string

        Get the string representation.
        """
        return _pyautolib.GURL_spec(self)

    __swig_destroy__ = _pyautolib.delete_GURL
    __del__ = lambda self : None;
GURL_swigregister = _pyautolib.GURL_swigregister
GURL_swigregister(GURL)
kDefaultApps = cvar.kDefaultApps
kDefaultAppsInstalled = cvar.kDefaultAppsInstalled
kHomePageIsNewTabPage = cvar.kHomePageIsNewTabPage
kHomePage = cvar.kHomePage
kHomePageChanged = cvar.kHomePageChanged
kIsGooglePlusUser = cvar.kIsGooglePlusUser
kSessionExitedCleanly = cvar.kSessionExitedCleanly
kSessionExitType = cvar.kSessionExitType
kRestoreOnStartup = cvar.kRestoreOnStartup
kURLsToRestoreOnStartup = cvar.kURLsToRestoreOnStartup
kRestoreOnStartupMigrated = cvar.kRestoreOnStartupMigrated
kDisableScreenshots = cvar.kDisableScreenshots
kApplicationLocale = cvar.kApplicationLocale
kGlobalDefaultCharset = cvar.kGlobalDefaultCharset
kWebKitGlobalDefaultFontSize = cvar.kWebKitGlobalDefaultFontSize
kWebKitGlobalDefaultFixedFontSize = cvar.kWebKitGlobalDefaultFixedFontSize
kWebKitGlobalMinimumFontSize = cvar.kWebKitGlobalMinimumFontSize
kWebKitGlobalMinimumLogicalFontSize = cvar.kWebKitGlobalMinimumLogicalFontSize
kWebKitGlobalJavascriptEnabled = cvar.kWebKitGlobalJavascriptEnabled
kWebKitGlobalJavascriptCanOpenWindowsAutomatically = cvar.kWebKitGlobalJavascriptCanOpenWindowsAutomatically
kWebKitGlobalLoadsImagesAutomatically = cvar.kWebKitGlobalLoadsImagesAutomatically
kWebKitGlobalPluginsEnabled = cvar.kWebKitGlobalPluginsEnabled
kWebKitGlobalStandardFontFamily = cvar.kWebKitGlobalStandardFontFamily
kWebKitGlobalFixedFontFamily = cvar.kWebKitGlobalFixedFontFamily
kWebKitGlobalSerifFontFamily = cvar.kWebKitGlobalSerifFontFamily
kWebKitGlobalSansSerifFontFamily = cvar.kWebKitGlobalSansSerifFontFamily
kWebKitGlobalCursiveFontFamily = cvar.kWebKitGlobalCursiveFontFamily
kWebKitGlobalFantasyFontFamily = cvar.kWebKitGlobalFantasyFontFamily
kWebKitOldStandardFontFamily = cvar.kWebKitOldStandardFontFamily
kWebKitOldFixedFontFamily = cvar.kWebKitOldFixedFontFamily
kWebKitOldSerifFontFamily = cvar.kWebKitOldSerifFontFamily
kWebKitOldSansSerifFontFamily = cvar.kWebKitOldSansSerifFontFamily
kWebKitOldCursiveFontFamily = cvar.kWebKitOldCursiveFontFamily
kWebKitOldFantasyFontFamily = cvar.kWebKitOldFantasyFontFamily
kDefaultCharset = cvar.kDefaultCharset
kAcceptLanguages = cvar.kAcceptLanguages
kStaticEncodings = cvar.kStaticEncodings
kShowBookmarkBar = cvar.kShowBookmarkBar
kBookmarkEditorExpandedNodes = cvar.kBookmarkEditorExpandedNodes
kWebKitCommonScript = cvar.kWebKitCommonScript
kWebKitStandardFontFamily = cvar.kWebKitStandardFontFamily
kWebKitFixedFontFamily = cvar.kWebKitFixedFontFamily
kWebKitSerifFontFamily = cvar.kWebKitSerifFontFamily
kWebKitSansSerifFontFamily = cvar.kWebKitSansSerifFontFamily
kWebKitCursiveFontFamily = cvar.kWebKitCursiveFontFamily
kWebKitFantasyFontFamily = cvar.kWebKitFantasyFontFamily
kWebKitPictographFontFamily = cvar.kWebKitPictographFontFamily
kWebKitScriptsForFontFamilyMaps = cvar.kWebKitScriptsForFontFamilyMaps
kWebKitScriptsForFontFamilyMapsLength = cvar.kWebKitScriptsForFontFamilyMapsLength
kWebKitStandardFontFamilyMap = cvar.kWebKitStandardFontFamilyMap
kWebKitFixedFontFamilyMap = cvar.kWebKitFixedFontFamilyMap
kWebKitSerifFontFamilyMap = cvar.kWebKitSerifFontFamilyMap
kWebKitSansSerifFontFamilyMap = cvar.kWebKitSansSerifFontFamilyMap
kWebKitCursiveFontFamilyMap = cvar.kWebKitCursiveFontFamilyMap
kWebKitFantasyFontFamilyMap = cvar.kWebKitFantasyFontFamilyMap
kWebKitPictographFontFamilyMap = cvar.kWebKitPictographFontFamilyMap
kWebKitStandardFontFamilyArabic = cvar.kWebKitStandardFontFamilyArabic
kWebKitFixedFontFamilyArabic = cvar.kWebKitFixedFontFamilyArabic
kWebKitSerifFontFamilyArabic = cvar.kWebKitSerifFontFamilyArabic
kWebKitSansSerifFontFamilyArabic = cvar.kWebKitSansSerifFontFamilyArabic
kWebKitStandardFontFamilyCyrillic = cvar.kWebKitStandardFontFamilyCyrillic
kWebKitFixedFontFamilyCyrillic = cvar.kWebKitFixedFontFamilyCyrillic
kWebKitSerifFontFamilyCyrillic = cvar.kWebKitSerifFontFamilyCyrillic
kWebKitSansSerifFontFamilyCyrillic = cvar.kWebKitSansSerifFontFamilyCyrillic
kWebKitStandardFontFamilyGreek = cvar.kWebKitStandardFontFamilyGreek
kWebKitFixedFontFamilyGreek = cvar.kWebKitFixedFontFamilyGreek
kWebKitSerifFontFamilyGreek = cvar.kWebKitSerifFontFamilyGreek
kWebKitSansSerifFontFamilyGreek = cvar.kWebKitSansSerifFontFamilyGreek
kWebKitStandardFontFamilyJapanese = cvar.kWebKitStandardFontFamilyJapanese
kWebKitFixedFontFamilyJapanese = cvar.kWebKitFixedFontFamilyJapanese
kWebKitSerifFontFamilyJapanese = cvar.kWebKitSerifFontFamilyJapanese
kWebKitSansSerifFontFamilyJapanese = cvar.kWebKitSansSerifFontFamilyJapanese
kWebKitStandardFontFamilyKorean = cvar.kWebKitStandardFontFamilyKorean
kWebKitFixedFontFamilyKorean = cvar.kWebKitFixedFontFamilyKorean
kWebKitSerifFontFamilyKorean = cvar.kWebKitSerifFontFamilyKorean
kWebKitSansSerifFontFamilyKorean = cvar.kWebKitSansSerifFontFamilyKorean
kWebKitCursiveFontFamilyKorean = cvar.kWebKitCursiveFontFamilyKorean
kWebKitStandardFontFamilySimplifiedHan = cvar.kWebKitStandardFontFamilySimplifiedHan
kWebKitFixedFontFamilySimplifiedHan = cvar.kWebKitFixedFontFamilySimplifiedHan
kWebKitSerifFontFamilySimplifiedHan = cvar.kWebKitSerifFontFamilySimplifiedHan
kWebKitSansSerifFontFamilySimplifiedHan = cvar.kWebKitSansSerifFontFamilySimplifiedHan
kWebKitStandardFontFamilyTraditionalHan = cvar.kWebKitStandardFontFamilyTraditionalHan
kWebKitFixedFontFamilyTraditionalHan = cvar.kWebKitFixedFontFamilyTraditionalHan
kWebKitSerifFontFamilyTraditionalHan = cvar.kWebKitSerifFontFamilyTraditionalHan
kWebKitSansSerifFontFamilyTraditionalHan = cvar.kWebKitSansSerifFontFamilyTraditionalHan
kWebKitDefaultFontSize = cvar.kWebKitDefaultFontSize
kWebKitDefaultFixedFontSize = cvar.kWebKitDefaultFixedFontSize
kWebKitMinimumFontSize = cvar.kWebKitMinimumFontSize
kWebKitMinimumLogicalFontSize = cvar.kWebKitMinimumLogicalFontSize
kWebKitJavascriptEnabled = cvar.kWebKitJavascriptEnabled
kWebKitWebSecurityEnabled = cvar.kWebKitWebSecurityEnabled
kWebKitJavascriptCanOpenWindowsAutomatically = cvar.kWebKitJavascriptCanOpenWindowsAutomatically
kWebKitLoadsImagesAutomatically = cvar.kWebKitLoadsImagesAutomatically
kWebKitPluginsEnabled = cvar.kWebKitPluginsEnabled
kWebKitDomPasteEnabled = cvar.kWebKitDomPasteEnabled
kWebKitShrinksStandaloneImagesToFit = cvar.kWebKitShrinksStandaloneImagesToFit
kWebKitInspectorSettings = cvar.kWebKitInspectorSettings
kWebKitUsesUniversalDetector = cvar.kWebKitUsesUniversalDetector
kWebKitTextAreasAreResizable = cvar.kWebKitTextAreasAreResizable
kWebKitJavaEnabled = cvar.kWebKitJavaEnabled
kWebkitTabsToLinks = cvar.kWebkitTabsToLinks
kWebKitAllowDisplayingInsecureContent = cvar.kWebKitAllowDisplayingInsecureContent
kWebKitAllowRunningInsecureContent = cvar.kWebKitAllowRunningInsecureContent
kPasswordManagerEnabled = cvar.kPasswordManagerEnabled
kPasswordManagerAllowShowPasswords = cvar.kPasswordManagerAllowShowPasswords
kPasswordGenerationEnabled = cvar.kPasswordGenerationEnabled
kAutologinEnabled = cvar.kAutologinEnabled
kReverseAutologinEnabled = cvar.kReverseAutologinEnabled
kReverseAutologinRejectedEmailList = cvar.kReverseAutologinRejectedEmailList
kSafeBrowsingEnabled = cvar.kSafeBrowsingEnabled
kSafeBrowsingReportingEnabled = cvar.kSafeBrowsingReportingEnabled
kSafeBrowsingProceedAnywayDisabled = cvar.kSafeBrowsingProceedAnywayDisabled
kIncognitoModeAvailability = cvar.kIncognitoModeAvailability
kSearchSuggestEnabled = cvar.kSearchSuggestEnabled
kConfirmToQuitEnabled = cvar.kConfirmToQuitEnabled
kCookieBehavior = cvar.kCookieBehavior
kSyncedDefaultSearchProviderGUID = cvar.kSyncedDefaultSearchProviderGUID
kDefaultSearchProviderEnabled = cvar.kDefaultSearchProviderEnabled
kDefaultSearchProviderSearchURL = cvar.kDefaultSearchProviderSearchURL
kDefaultSearchProviderSuggestURL = cvar.kDefaultSearchProviderSuggestURL
kDefaultSearchProviderInstantURL = cvar.kDefaultSearchProviderInstantURL
kDefaultSearchProviderIconURL = cvar.kDefaultSearchProviderIconURL
kDefaultSearchProviderEncodings = cvar.kDefaultSearchProviderEncodings
kDefaultSearchProviderName = cvar.kDefaultSearchProviderName
kDefaultSearchProviderKeyword = cvar.kDefaultSearchProviderKeyword
kDefaultSearchProviderID = cvar.kDefaultSearchProviderID
kDefaultSearchProviderPrepopulateID = cvar.kDefaultSearchProviderPrepopulateID
kDefaultSearchProviderAlternateURLs = cvar.kDefaultSearchProviderAlternateURLs
kSearchProviderOverrides = cvar.kSearchProviderOverrides
kSearchProviderOverridesVersion = cvar.kSearchProviderOverridesVersion
kPromptForDownload = cvar.kPromptForDownload
kAlternateErrorPagesEnabled = cvar.kAlternateErrorPagesEnabled
kDnsStartupPrefetchList = cvar.kDnsStartupPrefetchList
kDnsPrefetchingStartupList = cvar.kDnsPrefetchingStartupList
kDnsHostReferralList = cvar.kDnsHostReferralList
kDnsPrefetchingHostReferralList = cvar.kDnsPrefetchingHostReferralList
kDisableSpdy = cvar.kDisableSpdy
kHttpServerProperties = cvar.kHttpServerProperties
kSpdyServers = cvar.kSpdyServers
kAlternateProtocolServers = cvar.kAlternateProtocolServers
kDisabledSchemes = cvar.kDisabledSchemes
kUrlBlacklist = cvar.kUrlBlacklist
kUrlWhitelist = cvar.kUrlWhitelist
kInstantConfirmDialogShown = cvar.kInstantConfirmDialogShown
kInstantEnabled = cvar.kInstantEnabled
kInstantExtendedEnabled = cvar.kInstantExtendedEnabled
kInstantUIZeroSuggestUrlPrefix = cvar.kInstantUIZeroSuggestUrlPrefix
kMultipleProfilePrefMigration = cvar.kMultipleProfilePrefMigration
kNetworkPredictionEnabled = cvar.kNetworkPredictionEnabled
kDefaultAppsInstallState = cvar.kDefaultAppsInstallState
kIpcDisabledMessages = cvar.kIpcDisabledMessages
kShowHomeButton = cvar.kShowHomeButton
kRecentlySelectedEncoding = cvar.kRecentlySelectedEncoding
kDeleteBrowsingHistory = cvar.kDeleteBrowsingHistory
kDeleteDownloadHistory = cvar.kDeleteDownloadHistory
kDeleteCache = cvar.kDeleteCache
kDeleteCookies = cvar.kDeleteCookies
kDeletePasswords = cvar.kDeletePasswords
kDeleteFormData = cvar.kDeleteFormData
kDeleteHostedAppsData = cvar.kDeleteHostedAppsData
kDeauthorizeContentLicenses = cvar.kDeauthorizeContentLicenses
kEnableContinuousSpellcheck = cvar.kEnableContinuousSpellcheck
kSpeechRecognitionFilterProfanities = cvar.kSpeechRecognitionFilterProfanities
kSpeechRecognitionTrayNotificationShownContexts = cvar.kSpeechRecognitionTrayNotificationShownContexts
kEnabledLabsExperiments = cvar.kEnabledLabsExperiments
kEnableAutoSpellCorrect = cvar.kEnableAutoSpellCorrect
kSavingBrowserHistoryDisabled = cvar.kSavingBrowserHistoryDisabled
kForceSafeSearch = cvar.kForceSafeSearch
kDeleteTimePeriod = cvar.kDeleteTimePeriod
kCurrentThemePackFilename = cvar.kCurrentThemePackFilename
kCurrentThemeID = cvar.kCurrentThemeID
kCurrentThemeImages = cvar.kCurrentThemeImages
kCurrentThemeColors = cvar.kCurrentThemeColors
kCurrentThemeTints = cvar.kCurrentThemeTints
kCurrentThemeDisplayProperties = cvar.kCurrentThemeDisplayProperties
kExtensionsUIDeveloperMode = cvar.kExtensionsUIDeveloperMode
kExtensionToolbarSize = cvar.kExtensionToolbarSize
kExtensionCommands = cvar.kExtensionCommands
kExtensionsSideloadWipeoutBubbleShown = cvar.kExtensionsSideloadWipeoutBubbleShown
kPluginsLastInternalDirectory = cvar.kPluginsLastInternalDirectory
kPluginsPluginsList = cvar.kPluginsPluginsList
kPluginsDisabledPlugins = cvar.kPluginsDisabledPlugins
kPluginsDisabledPluginsExceptions = cvar.kPluginsDisabledPluginsExceptions
kPluginsEnabledPlugins = cvar.kPluginsEnabledPlugins
kPluginsEnabledInternalPDF = cvar.kPluginsEnabledInternalPDF
kPluginsEnabledNaCl = cvar.kPluginsEnabledNaCl
kPluginsMigratedToPepperFlash = cvar.kPluginsMigratedToPepperFlash
kPluginsShowDetails = cvar.kPluginsShowDetails
kPluginsAllowOutdated = cvar.kPluginsAllowOutdated
kPluginsAlwaysAuthorize = cvar.kPluginsAlwaysAuthorize
kCheckDefaultBrowser = cvar.kCheckDefaultBrowser
kDefaultBrowserSettingEnabled = cvar.kDefaultBrowserSettingEnabled
kUseCustomChromeFrame = cvar.kUseCustomChromeFrame
kShowOmniboxSearchHint = cvar.kShowOmniboxSearchHint
kDesktopNotificationPosition = cvar.kDesktopNotificationPosition
kDefaultContentSettings = cvar.kDefaultContentSettings
kContentSettingsClearOnExitMigrated = cvar.kContentSettingsClearOnExitMigrated
kContentSettingsVersion = cvar.kContentSettingsVersion
kContentSettingsPatternPairs = cvar.kContentSettingsPatternPairs
kContentSettingsDefaultWhitelistVersion = cvar.kContentSettingsDefaultWhitelistVersion
kContentSettingsPluginWhitelist = cvar.kContentSettingsPluginWhitelist
kBlockThirdPartyCookies = cvar.kBlockThirdPartyCookies
kClearSiteDataOnExit = cvar.kClearSiteDataOnExit
kDefaultZoomLevel = cvar.kDefaultZoomLevel
kPerHostZoomLevels = cvar.kPerHostZoomLevels
kAutofillEnabled = cvar.kAutofillEnabled
kAutofillAuxiliaryProfilesEnabled = cvar.kAutofillAuxiliaryProfilesEnabled
kAutofillPositiveUploadRate = cvar.kAutofillPositiveUploadRate
kAutofillNegativeUploadRate = cvar.kAutofillNegativeUploadRate
kAutofillPersonalDataManagerFirstRun = cvar.kAutofillPersonalDataManagerFirstRun
kEditBookmarksEnabled = cvar.kEditBookmarksEnabled
kEnableTranslate = cvar.kEnableTranslate
kPinnedTabs = cvar.kPinnedTabs
kDisable3DAPIs = cvar.kDisable3DAPIs
kEnableHyperlinkAuditing = cvar.kEnableHyperlinkAuditing
kEnableReferrers = cvar.kEnableReferrers
kEnableDoNotTrack = cvar.kEnableDoNotTrack
kImportBookmarks = cvar.kImportBookmarks
kImportHistory = cvar.kImportHistory
kImportHomepage = cvar.kImportHomepage
kImportSearchEngine = cvar.kImportSearchEngine
kImportSavedPasswords = cvar.kImportSavedPasswords
kEnterpriseWebStoreURL = cvar.kEnterpriseWebStoreURL
kEnterpriseWebStoreName = cvar.kEnterpriseWebStoreName
kProfileAvatarIndex = cvar.kProfileAvatarIndex
kProfileName = cvar.kProfileName
kProfileIsManaged = cvar.kProfileIsManaged
kInvertNotificationShown = cvar.kInvertNotificationShown
kPrintingEnabled = cvar.kPrintingEnabled
kPrintPreviewDisabled = cvar.kPrintPreviewDisabled
kDefaultManagedModeFilteringBehavior = cvar.kDefaultManagedModeFilteringBehavior
kCertRevocationCheckingEnabled = cvar.kCertRevocationCheckingEnabled
kSSLVersionMin = cvar.kSSLVersionMin
kSSLVersionMax = cvar.kSSLVersionMax
kCipherSuiteBlacklist = cvar.kCipherSuiteBlacklist
kEnableOriginBoundCerts = cvar.kEnableOriginBoundCerts
kDisableSSLRecordSplitting = cvar.kDisableSSLRecordSplitting
kEnableMemoryInfo = cvar.kEnableMemoryInfo
kGLVendorString = cvar.kGLVendorString
kGLRendererString = cvar.kGLRendererString
kGLVersionString = cvar.kGLVersionString
kMetricsClientID = cvar.kMetricsClientID
kMetricsSessionID = cvar.kMetricsSessionID
kMetricsLowEntropySource = cvar.kMetricsLowEntropySource
kMetricsClientIDTimestamp = cvar.kMetricsClientIDTimestamp
kMetricsReportingEnabled = cvar.kMetricsReportingEnabled
kMetricsInitialLogsXml = cvar.kMetricsInitialLogsXml
kMetricsInitialLogsProto = cvar.kMetricsInitialLogsProto
kMetricsOngoingLogsXml = cvar.kMetricsOngoingLogsXml
kMetricsOngoingLogsProto = cvar.kMetricsOngoingLogsProto
kBookmarkPromptEnabled = cvar.kBookmarkPromptEnabled
kBookmarkPromptImpressionCount = cvar.kBookmarkPromptImpressionCount
kVariationsSeed = cvar.kVariationsSeed
kVariationsSeedDate = cvar.kVariationsSeedDate
kProfileLastUsed = cvar.kProfileLastUsed
kProfilesLastActive = cvar.kProfilesLastActive
kProfilesNumCreated = cvar.kProfilesNumCreated
kProfileInfoCache = cvar.kProfileInfoCache
kProfileCreatedByVersion = cvar.kProfileCreatedByVersion
kProfileMetrics = cvar.kProfileMetrics
kProfilePrefix = cvar.kProfilePrefix
kStabilityExitedCleanly = cvar.kStabilityExitedCleanly
kStabilityStatsVersion = cvar.kStabilityStatsVersion
kStabilityStatsBuildTime = cvar.kStabilityStatsBuildTime
kStabilitySessionEndCompleted = cvar.kStabilitySessionEndCompleted
kStabilityLaunchCount = cvar.kStabilityLaunchCount
kStabilityCrashCount = cvar.kStabilityCrashCount
kStabilityIncompleteSessionEndCount = cvar.kStabilityIncompleteSessionEndCount
kStabilityPageLoadCount = cvar.kStabilityPageLoadCount
kStabilityRendererCrashCount = cvar.kStabilityRendererCrashCount
kStabilityExtensionRendererCrashCount = cvar.kStabilityExtensionRendererCrashCount
kStabilityLaunchTimeSec = cvar.kStabilityLaunchTimeSec
kStabilityLastTimestampSec = cvar.kStabilityLastTimestampSec
kStabilityRendererHangCount = cvar.kStabilityRendererHangCount
kStabilityChildProcessCrashCount = cvar.kStabilityChildProcessCrashCount
kStabilityOtherUserCrashCount = cvar.kStabilityOtherUserCrashCount
kStabilityKernelCrashCount = cvar.kStabilityKernelCrashCount
kStabilitySystemUncleanShutdownCount = cvar.kStabilitySystemUncleanShutdownCount
kStabilityBreakpadRegistrationSuccess = cvar.kStabilityBreakpadRegistrationSuccess
kStabilityBreakpadRegistrationFail = cvar.kStabilityBreakpadRegistrationFail
kStabilityDebuggerPresent = cvar.kStabilityDebuggerPresent
kStabilityDebuggerNotPresent = cvar.kStabilityDebuggerNotPresent
kStabilityPluginStats = cvar.kStabilityPluginStats
kStabilityPluginName = cvar.kStabilityPluginName
kStabilityPluginLaunches = cvar.kStabilityPluginLaunches
kStabilityPluginInstances = cvar.kStabilityPluginInstances
kStabilityPluginCrashes = cvar.kStabilityPluginCrashes
kStabilityPluginLoadingErrors = cvar.kStabilityPluginLoadingErrors
kUninstallMetricsPageLoadCount = cvar.kUninstallMetricsPageLoadCount
kUninstallLaunchCount = cvar.kUninstallLaunchCount
kUninstallMetricsInstallDate = cvar.kUninstallMetricsInstallDate
kUninstallMetricsUptimeSec = cvar.kUninstallMetricsUptimeSec
kUninstallLastLaunchTimeSec = cvar.kUninstallLastLaunchTimeSec
kUninstallLastObservedRunTimeSec = cvar.kUninstallLastObservedRunTimeSec
kBrowserWindowPlacement = cvar.kBrowserWindowPlacement
kTaskManagerWindowPlacement = cvar.kTaskManagerWindowPlacement
kKeywordEditorWindowPlacement = cvar.kKeywordEditorWindowPlacement
kPreferencesWindowPlacement = cvar.kPreferencesWindowPlacement
kMemoryCacheSize = cvar.kMemoryCacheSize
kDownloadDefaultDirectory = cvar.kDownloadDefaultDirectory
kDownloadExtensionsToOpen = cvar.kDownloadExtensionsToOpen
kDownloadDirUpgraded = cvar.kDownloadDirUpgraded
kSaveFileDefaultDirectory = cvar.kSaveFileDefaultDirectory
kSaveFileType = cvar.kSaveFileType
kAllowFileSelectionDialogs = cvar.kAllowFileSelectionDialogs
kDefaultTasksByMimeType = cvar.kDefaultTasksByMimeType
kDefaultTasksBySuffix = cvar.kDefaultTasksBySuffix
kSelectFileLastDirectory = cvar.kSelectFileLastDirectory
kHungPluginDetectFrequency = cvar.kHungPluginDetectFrequency
kPluginMessageResponseTimeout = cvar.kPluginMessageResponseTimeout
kSpellCheckDictionary = cvar.kSpellCheckDictionary
kSpellCheckConfirmDialogShown = cvar.kSpellCheckConfirmDialogShown
kSpellCheckUseSpellingService = cvar.kSpellCheckUseSpellingService
kExcludedSchemes = cvar.kExcludedSchemes
kSafeBrowsingClientKey = cvar.kSafeBrowsingClientKey
kSafeBrowsingWrappedKey = cvar.kSafeBrowsingWrappedKey
kOptionsWindowLastTabIndex = cvar.kOptionsWindowLastTabIndex
kContentSettingsWindowLastTabIndex = cvar.kContentSettingsWindowLastTabIndex
kCertificateManagerWindowLastTabIndex = cvar.kCertificateManagerWindowLastTabIndex
kShowFirstRunBubbleOption = cvar.kShowFirstRunBubbleOption
kShouldShowWelcomePage = cvar.kShouldShowWelcomePage
kLastKnownGoogleURL = cvar.kLastKnownGoogleURL
kLastPromptedGoogleURL = cvar.kLastPromptedGoogleURL
kLastKnownIntranetRedirectOrigin = cvar.kLastKnownIntranetRedirectOrigin
kCountryIDAtInstall = cvar.kCountryIDAtInstall
kGeoIDAtInstall = cvar.kGeoIDAtInstall
kShutdownType = cvar.kShutdownType
kShutdownNumProcesses = cvar.kShutdownNumProcesses
kShutdownNumProcessesSlow = cvar.kShutdownNumProcessesSlow
kRestartLastSessionOnShutdown = cvar.kRestartLastSessionOnShutdown
kWasRestarted = cvar.kWasRestarted
kNumBookmarksOnBookmarkBar = cvar.kNumBookmarksOnBookmarkBar
kNumFoldersOnBookmarkBar = cvar.kNumFoldersOnBookmarkBar
kNumBookmarksInOtherBookmarkFolder = cvar.kNumBookmarksInOtherBookmarkFolder
kNumFoldersInOtherBookmarkFolder = cvar.kNumFoldersInOtherBookmarkFolder
kNumKeywords = cvar.kNumKeywords
kDisableVideoAndChat = cvar.kDisableVideoAndChat
kDisableExtensions = cvar.kDisableExtensions
kDisablePluginFinder = cvar.kDisablePluginFinder
kBrowserActionContainerWidth = cvar.kBrowserActionContainerWidth
kLastExtensionsUpdateCheck = cvar.kLastExtensionsUpdateCheck
kNextExtensionsUpdateCheck = cvar.kNextExtensionsUpdateCheck
kExtensionAlertsInitializedPref = cvar.kExtensionAlertsInitializedPref
kExtensionAllowedInstallSites = cvar.kExtensionAllowedInstallSites
kExtensionAllowedTypes = cvar.kExtensionAllowedTypes
kExtensionBlacklistUpdateVersion = cvar.kExtensionBlacklistUpdateVersion
kExtensionInstallAllowList = cvar.kExtensionInstallAllowList
kExtensionInstallDenyList = cvar.kExtensionInstallDenyList
kExtensionInstallForceList = cvar.kExtensionInstallForceList
kExtensionStorageGarbageCollect = cvar.kExtensionStorageGarbageCollect
kNtpTipsResourceServer = cvar.kNtpTipsResourceServer
kNtpCollapsedForeignSessions = cvar.kNtpCollapsedForeignSessions
kNtpMostVisitedURLsBlacklist = cvar.kNtpMostVisitedURLsBlacklist
kNtpPromoResourceCacheUpdate = cvar.kNtpPromoResourceCacheUpdate
kNtpDateResourceServer = cvar.kNtpDateResourceServer
kNtpShownBookmarksFolder = cvar.kNtpShownBookmarksFolder
kNtpShownPage = cvar.kNtpShownPage
kNtpPromoDesktopSessionFound = cvar.kNtpPromoDesktopSessionFound
kNtpWebStoreEnabled = cvar.kNtpWebStoreEnabled
kNtpAppPageNames = cvar.kNtpAppPageNames
kDevToolsDisabled = cvar.kDevToolsDisabled
kDevToolsDockSide = cvar.kDevToolsDockSide
kDevToolsEditedFiles = cvar.kDevToolsEditedFiles
kDevToolsHSplitLocation = cvar.kDevToolsHSplitLocation
kDevToolsOpenDocked = cvar.kDevToolsOpenDocked
kDevToolsVSplitLocation = cvar.kDevToolsVSplitLocation
kSyncLastSyncedTime = cvar.kSyncLastSyncedTime
kSyncHasSetupCompleted = cvar.kSyncHasSetupCompleted
kSyncKeepEverythingSynced = cvar.kSyncKeepEverythingSynced
kSyncBookmarks = cvar.kSyncBookmarks
kSyncPasswords = cvar.kSyncPasswords
kSyncPreferences = cvar.kSyncPreferences
kSyncAppNotifications = cvar.kSyncAppNotifications
kSyncAppSettings = cvar.kSyncAppSettings
kSyncApps = cvar.kSyncApps
kSyncAutofill = cvar.kSyncAutofill
kSyncAutofillProfile = cvar.kSyncAutofillProfile
kSyncThemes = cvar.kSyncThemes
kSyncTypedUrls = cvar.kSyncTypedUrls
kSyncExtensions = cvar.kSyncExtensions
kSyncExtensionSettings = cvar.kSyncExtensionSettings
kSyncHistoryDeleteDirectives = cvar.kSyncHistoryDeleteDirectives
kSyncManaged = cvar.kSyncManaged
kSyncSearchEngines = cvar.kSyncSearchEngines
kSyncSessions = cvar.kSyncSessions
kSyncSuppressStart = cvar.kSyncSuppressStart
kGoogleServicesLastUsername = cvar.kGoogleServicesLastUsername
kGoogleServicesUsername = cvar.kGoogleServicesUsername
kGoogleServicesUsernamePattern = cvar.kGoogleServicesUsernamePattern
kSyncUsingSecondaryPassphrase = cvar.kSyncUsingSecondaryPassphrase
kSyncEncryptionBootstrapToken = cvar.kSyncEncryptionBootstrapToken
kSyncKeystoreEncryptionBootstrapToken = cvar.kSyncKeystoreEncryptionBootstrapToken
kSyncAcknowledgedSyncTypes = cvar.kSyncAcknowledgedSyncTypes
kSyncMaxInvalidationVersions = cvar.kSyncMaxInvalidationVersions
kSyncSessionsGUID = cvar.kSyncSessionsGUID
kInvalidatorInvalidationState = cvar.kInvalidatorInvalidationState
kInvalidatorMaxInvalidationVersions = cvar.kInvalidatorMaxInvalidationVersions
kSyncPromoStartupCount = cvar.kSyncPromoStartupCount
kSyncPromoViewCount = cvar.kSyncPromoViewCount
kSyncPromoUserSkipped = cvar.kSyncPromoUserSkipped
kSyncPromoShowOnFirstRunAllowed = cvar.kSyncPromoShowOnFirstRunAllowed
kSyncPromoShowNTPBubble = cvar.kSyncPromoShowNTPBubble
kSyncPromoErrorMessage = cvar.kSyncPromoErrorMessage
kProfileGAIAInfoUpdateTime = cvar.kProfileGAIAInfoUpdateTime
kProfileGAIAInfoPictureURL = cvar.kProfileGAIAInfoPictureURL
kWebAppCreateOnDesktop = cvar.kWebAppCreateOnDesktop
kWebAppCreateInAppsMenu = cvar.kWebAppCreateInAppsMenu
kWebAppCreateInQuickLaunchBar = cvar.kWebAppCreateInQuickLaunchBar
kGeolocationAccessToken = cvar.kGeolocationAccessToken
kDefaultAudioCaptureDevice = cvar.kDefaultAudioCaptureDevice
kDefaultVideoCaptureDevice = cvar.kDefaultVideoCaptureDevice
kRemoteAccessHostFirewallTraversal = cvar.kRemoteAccessHostFirewallTraversal
kRemoteAccessHostRequireTwoFactor = cvar.kRemoteAccessHostRequireTwoFactor
kRemoteAccessHostDomain = cvar.kRemoteAccessHostDomain
kRemoteAccessHostTalkGadgetPrefix = cvar.kRemoteAccessHostTalkGadgetPrefix
kRemoteAccessHostRequireCurtain = cvar.kRemoteAccessHostRequireCurtain
kPrintPreviewStickySettings = cvar.kPrintPreviewStickySettings
kCloudPrintRoot = cvar.kCloudPrintRoot
kCloudPrintServiceURL = cvar.kCloudPrintServiceURL
kCloudPrintSigninURL = cvar.kCloudPrintSigninURL
kCloudPrintDialogWidth = cvar.kCloudPrintDialogWidth
kCloudPrintDialogHeight = cvar.kCloudPrintDialogHeight
kCloudPrintSigninDialogWidth = cvar.kCloudPrintSigninDialogWidth
kCloudPrintSigninDialogHeight = cvar.kCloudPrintSigninDialogHeight
kCloudPrintProxyEnabled = cvar.kCloudPrintProxyEnabled
kCloudPrintProxyId = cvar.kCloudPrintProxyId
kCloudPrintAuthToken = cvar.kCloudPrintAuthToken
kCloudPrintXMPPAuthToken = cvar.kCloudPrintXMPPAuthToken
kCloudPrintEmail = cvar.kCloudPrintEmail
kCloudPrintPrintSystemSettings = cvar.kCloudPrintPrintSystemSettings
kCloudPrintEnableJobPoll = cvar.kCloudPrintEnableJobPoll
kCloudPrintRobotRefreshToken = cvar.kCloudPrintRobotRefreshToken
kCloudPrintRobotEmail = cvar.kCloudPrintRobotEmail
kCloudPrintConnectNewPrinters = cvar.kCloudPrintConnectNewPrinters
kCloudPrintXmppPingEnabled = cvar.kCloudPrintXmppPingEnabled
kCloudPrintXmppPingTimeout = cvar.kCloudPrintXmppPingTimeout
kCloudPrintPrinterBlacklist = cvar.kCloudPrintPrinterBlacklist
kCloudPrintSubmitEnabled = cvar.kCloudPrintSubmitEnabled
kChromeToMobileDeviceList = cvar.kChromeToMobileDeviceList
kProxy = cvar.kProxy
kMaxConnectionsPerProxy = cvar.kMaxConnectionsPerProxy
kManagedDefaultCookiesSetting = cvar.kManagedDefaultCookiesSetting
kManagedDefaultImagesSetting = cvar.kManagedDefaultImagesSetting
kManagedDefaultJavaScriptSetting = cvar.kManagedDefaultJavaScriptSetting
kManagedDefaultPluginsSetting = cvar.kManagedDefaultPluginsSetting
kManagedDefaultPopupsSetting = cvar.kManagedDefaultPopupsSetting
kManagedDefaultGeolocationSetting = cvar.kManagedDefaultGeolocationSetting
kManagedDefaultNotificationsSetting = cvar.kManagedDefaultNotificationsSetting
kManagedDefaultMediaStreamSetting = cvar.kManagedDefaultMediaStreamSetting
kManagedCookiesAllowedForUrls = cvar.kManagedCookiesAllowedForUrls
kManagedCookiesBlockedForUrls = cvar.kManagedCookiesBlockedForUrls
kManagedCookiesSessionOnlyForUrls = cvar.kManagedCookiesSessionOnlyForUrls
kManagedImagesAllowedForUrls = cvar.kManagedImagesAllowedForUrls
kManagedImagesBlockedForUrls = cvar.kManagedImagesBlockedForUrls
kManagedJavaScriptAllowedForUrls = cvar.kManagedJavaScriptAllowedForUrls
kManagedJavaScriptBlockedForUrls = cvar.kManagedJavaScriptBlockedForUrls
kManagedPluginsAllowedForUrls = cvar.kManagedPluginsAllowedForUrls
kManagedPluginsBlockedForUrls = cvar.kManagedPluginsBlockedForUrls
kManagedPopupsAllowedForUrls = cvar.kManagedPopupsAllowedForUrls
kManagedPopupsBlockedForUrls = cvar.kManagedPopupsBlockedForUrls
kManagedNotificationsAllowedForUrls = cvar.kManagedNotificationsAllowedForUrls
kManagedNotificationsBlockedForUrls = cvar.kManagedNotificationsBlockedForUrls
kManagedAutoSelectCertificateForUrls = cvar.kManagedAutoSelectCertificateForUrls
kAudioCaptureAllowed = cvar.kAudioCaptureAllowed
kVideoCaptureAllowed = cvar.kVideoCaptureAllowed
kClearPluginLSODataEnabled = cvar.kClearPluginLSODataEnabled
kPepperFlashSettingsEnabled = cvar.kPepperFlashSettingsEnabled
kDiskCacheDir = cvar.kDiskCacheDir
kDiskCacheSize = cvar.kDiskCacheSize
kMediaCacheSize = cvar.kMediaCacheSize
kChromeOsReleaseChannel = cvar.kChromeOsReleaseChannel
kTabStripLayoutType = cvar.kTabStripLayoutType
kRegisteredBackgroundContents = cvar.kRegisteredBackgroundContents
kShownAutoLaunchInfobar = cvar.kShownAutoLaunchInfobar
kAuthSchemes = cvar.kAuthSchemes
kDisableAuthNegotiateCnameLookup = cvar.kDisableAuthNegotiateCnameLookup
kEnableAuthNegotiatePort = cvar.kEnableAuthNegotiatePort
kAuthServerWhitelist = cvar.kAuthServerWhitelist
kAuthNegotiateDelegateWhitelist = cvar.kAuthNegotiateDelegateWhitelist
kGSSAPILibraryName = cvar.kGSSAPILibraryName
kSpdyProxyOrigin = cvar.kSpdyProxyOrigin
kAllowCrossOriginAuthPrompt = cvar.kAllowCrossOriginAuthPrompt
kBuiltInDnsClientEnabled = cvar.kBuiltInDnsClientEnabled
kHttpReceivedContentLength = cvar.kHttpReceivedContentLength
kHttpOriginalContentLength = cvar.kHttpOriginalContentLength
kRegisteredProtocolHandlers = cvar.kRegisteredProtocolHandlers
kIgnoredProtocolHandlers = cvar.kIgnoredProtocolHandlers
kCustomHandlersEnabled = cvar.kCustomHandlersEnabled
kUserCreatedLoginItem = cvar.kUserCreatedLoginItem
kUserRemovedLoginItem = cvar.kUserRemovedLoginItem
kBackgroundModeEnabled = cvar.kBackgroundModeEnabled
kDevicePolicyRefreshRate = cvar.kDevicePolicyRefreshRate
kUserPolicyRefreshRate = cvar.kUserPolicyRefreshRate
kLoadCloudPolicyOnSignin = cvar.kLoadCloudPolicyOnSignin
kFactoryResetRequested = cvar.kFactoryResetRequested
kRecoveryComponentVersion = cvar.kRecoveryComponentVersion
kComponentUpdaterState = cvar.kComponentUpdaterState
kMediaGalleriesUniqueId = cvar.kMediaGalleriesUniqueId
kMediaGalleriesRememberedGalleries = cvar.kMediaGalleriesRememberedGalleries
kInManagedMode = cvar.kInManagedMode
kNetworkProfileWarningsLeft = cvar.kNetworkProfileWarningsLeft
kNetworkProfileLastWarningTime = cvar.kNetworkProfileLastWarningTime
kLastPolicyStatisticsUpdate = cvar.kLastPolicyStatisticsUpdate
CERT_STATUS_ALL_ERRORS = cvar.CERT_STATUS_ALL_ERRORS
CERT_STATUS_COMMON_NAME_INVALID = cvar.CERT_STATUS_COMMON_NAME_INVALID
CERT_STATUS_DATE_INVALID = cvar.CERT_STATUS_DATE_INVALID
CERT_STATUS_AUTHORITY_INVALID = cvar.CERT_STATUS_AUTHORITY_INVALID
CERT_STATUS_NO_REVOCATION_MECHANISM = cvar.CERT_STATUS_NO_REVOCATION_MECHANISM
CERT_STATUS_UNABLE_TO_CHECK_REVOCATION = cvar.CERT_STATUS_UNABLE_TO_CHECK_REVOCATION
CERT_STATUS_REVOKED = cvar.CERT_STATUS_REVOKED
CERT_STATUS_INVALID = cvar.CERT_STATUS_INVALID
CERT_STATUS_WEAK_SIGNATURE_ALGORITHM = cvar.CERT_STATUS_WEAK_SIGNATURE_ALGORITHM
CERT_STATUS_NON_UNIQUE_NAME = cvar.CERT_STATUS_NON_UNIQUE_NAME
CERT_STATUS_WEAK_KEY = cvar.CERT_STATUS_WEAK_KEY
CERT_STATUS_IS_EV = cvar.CERT_STATUS_IS_EV
CERT_STATUS_REV_CHECKING_ENABLED = cvar.CERT_STATUS_REV_CHECKING_ENABLED

class FilePath(_object):
    """Represent a file path. Call value() to get the string."""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FilePath, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FilePath, name)
    __repr__ = _swig_repr
    def value(self):
        """
        value(self) -> StringType

        Get the string representation.
        """
        return _pyautolib.FilePath_value(self)

    def __init__(self, *args): 
        """
        __init__(self) -> FilePath
        __init__(self, StringType path) -> FilePath

        Construct an empty FilePath from a string.
        """
        this = _pyautolib.new_FilePath(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pyautolib.delete_FilePath
    __del__ = lambda self : None;
FilePath_swigregister = _pyautolib.FilePath_swigregister
FilePath_swigregister(FilePath)

class PyUITestSuiteBase(_object):
    """Proxy of C++ PyUITestSuiteBase class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PyUITestSuiteBase, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PyUITestSuiteBase, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self, int argc) -> PyUITestSuiteBase

        Create the suite.
        """
        this = _pyautolib.new_PyUITestSuiteBase(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pyautolib.delete_PyUITestSuiteBase
    __del__ = lambda self : None;
    def InitializeWithPath(self, *args):
        """
        InitializeWithPath(self, FilePath browser_dir)

        Initialize from the path to browser dir.
        """
        return _pyautolib.PyUITestSuiteBase_InitializeWithPath(self, *args)

    def SetCrSourceRoot(self, *args):
        """
        SetCrSourceRoot(self, FilePath path)

        Set chrome source root path, used in some tests
        """
        return _pyautolib.PyUITestSuiteBase_SetCrSourceRoot(self, *args)

PyUITestSuiteBase_swigregister = _pyautolib.PyUITestSuiteBase_swigregister
PyUITestSuiteBase_swigregister(PyUITestSuiteBase)

class PyUITestBase(_object):
    """Proxy of C++ PyUITestBase class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PyUITestBase, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PyUITestBase, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, bool clear_profile, wstring homepage) -> PyUITestBase"""
        this = _pyautolib.new_PyUITestBase(*args)
        try: self.this.append(this)
        except: self.this = this
    def Initialize(self, *args):
        """
        Initialize(self, FilePath browser_dir)

        Initialize the entire setup. Should be called before launching the browser. For internal use.
        """
        return _pyautolib.PyUITestBase_Initialize(self, *args)

    def AppendBrowserLaunchSwitch(self, *args):
        """
        AppendBrowserLaunchSwitch(self, char name)
        AppendBrowserLaunchSwitch(self, char name, char value)

        Appends a command-line switch (with associated value if given) to the list of switches to be passed to the browser upon launch. Should be called before launching the browser. For internal use only.
        """
        return _pyautolib.PyUITestBase_AppendBrowserLaunchSwitch(self, *args)

    def BeginTracing(self, *args):
        """
        BeginTracing(self, string categories) -> bool

        Begins tracing with the given category string.
        """
        return _pyautolib.PyUITestBase_BeginTracing(self, *args)

    def EndTracing(self):
        """
        EndTracing(self) -> string

        Ends tracing and returns the collected events.
        """
        return _pyautolib.PyUITestBase_EndTracing(self)

    def UseNamedChannelID(self, *args):
        """UseNamedChannelID(self, string named_channel_id)"""
        return _pyautolib.PyUITestBase_UseNamedChannelID(self, *args)

    def SetUp(self):
        """
        SetUp(self)

        Fires up the browser and opens a window.
        """
        return _pyautolib.PyUITestBase_SetUp(self)

    def TearDown(self):
        """
        TearDown(self)

        Closes all windows and destroys the browser.
        """
        return _pyautolib.PyUITestBase_TearDown(self)

    def LaunchBrowserAndServer(self):
        """
        LaunchBrowserAndServer(self)

        Launches the browser and IPC testing server.
        """
        return _pyautolib.PyUITestBase_LaunchBrowserAndServer(self)

    def CloseBrowserAndServer(self):
        """
        CloseBrowserAndServer(self)

        Closes the browser and IPC testing server.
        """
        return _pyautolib.PyUITestBase_CloseBrowserAndServer(self)

    def get_clear_profile(self):
        """
        get_clear_profile(self) -> bool

        Determine if the profile is set to be cleared on next startup.
        """
        return _pyautolib.PyUITestBase_get_clear_profile(self)

    def set_clear_profile(self, *args):
        """
        set_clear_profile(self, bool clear_profile)

        If False, sets the flag so that the profile is not cleared on next startup. Useful for persisting profile across restarts. By default the state is True, to clear profile.
        """
        return _pyautolib.PyUITestBase_set_clear_profile(self, *args)

    def user_data_dir(self):
        """
        user_data_dir(self) -> FilePath

        Get the path to profile directory.
        """
        return _pyautolib.PyUITestBase_user_data_dir(self)

    def _SendJSONRequest(self, *args):
        """
        _SendJSONRequest(self, int window_index, string request, int timeout) -> string

        Send a sync JSON request to Chrome.  Returns a JSON dict as a response.  Given timeout in milliseconds.Internal method.
        """
        return _pyautolib.PyUITestBase__SendJSONRequest(self, *args)

    def CheckErrorsAndCrashes(self):
        """CheckErrorsAndCrashes(self) -> string"""
        return _pyautolib.PyUITestBase_CheckErrorsAndCrashes(self)

    __swig_destroy__ = _pyautolib.delete_PyUITestBase
    __del__ = lambda self : None;
PyUITestBase_swigregister = _pyautolib.PyUITestBase_swigregister
PyUITestBase_swigregister(PyUITestBase)

class TestServer(_object):
    """TestServer. Serves files in data dir over a local http server"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TestServer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TestServer, name)
    __repr__ = _swig_repr
    TYPE_FTP = _pyautolib.TestServer_TYPE_FTP
    TYPE_HTTP = _pyautolib.TestServer_TYPE_HTTP
    TYPE_HTTPS = _pyautolib.TestServer_TYPE_HTTPS
    TYPE_SYNC = _pyautolib.TestServer_TYPE_SYNC
    def __init__(self, *args): 
        """
        __init__(self, Type type, string host, FilePath document_root) -> TestServer
        __init__(self, Type type, SSLOptions ssl_options, FilePath document_root) -> TestServer
        """
        this = _pyautolib.new_TestServer(*args)
        try: self.this.append(this)
        except: self.this = this
    def Start(self):
        """
        Start(self) -> bool

        Start TestServer over an ephemeral port
        """
        return _pyautolib.TestServer_Start(self)

    def Stop(self):
        """
        Stop(self) -> bool

        Stop TestServer
        """
        return _pyautolib.TestServer_Stop(self)

    def document_root(self):
        """
        document_root(self) -> FilePath

        Get FilePath to the document root
        """
        return _pyautolib.TestServer_document_root(self)

    def GetScheme(self):
        """GetScheme(self) -> string"""
        return _pyautolib.TestServer_GetScheme(self)

    def GetURL(self, *args):
        """
        GetURL(self, string path) -> GURL

        Get URL for a file path
        """
        return _pyautolib.TestServer_GetURL(self, *args)

    def GetPort(self):
        """
        GetPort(self) -> int

        Get port number.
        """
        return _pyautolib.TestServer_GetPort(self)

    def GetSyncXmppPort(self):
        """
        GetSyncXmppPort(self) -> int

        Get xmpp port number in case of sync server.
        """
        return _pyautolib.TestServer_GetSyncXmppPort(self)

    __swig_destroy__ = _pyautolib.delete_TestServer
    __del__ = lambda self : None;
TestServer_swigregister = _pyautolib.TestServer_swigregister
TestServer_swigregister(TestServer)

class SSLOptions(_object):
    """SSLOptions. Sets one of three types of a cert"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SSLOptions, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SSLOptions, name)
    __repr__ = _swig_repr
    CERT_OK = _pyautolib.SSLOptions_CERT_OK
    CERT_MISMATCHED_NAME = _pyautolib.SSLOptions_CERT_MISMATCHED_NAME
    CERT_EXPIRED = _pyautolib.SSLOptions_CERT_EXPIRED
    def __init__(self, *args): 
        """
        __init__(self, ServerCertificate cert) -> SSLOptions

        SSLOptions. Sets one of three types of a cert
        """
        this = _pyautolib.new_SSLOptions(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pyautolib.delete_SSLOptions
    __del__ = lambda self : None;
SSLOptions_swigregister = _pyautolib.SSLOptions_swigregister
SSLOptions_swigregister(SSLOptions)

class int_ptr(_object):
    """Proxy of C++ int_ptr class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, int_ptr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, int_ptr, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> int_ptr"""
        this = _pyautolib.new_int_ptr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pyautolib.delete_int_ptr
    __del__ = lambda self : None;
    def assign(self, *args):
        """assign(self, int value)"""
        return _pyautolib.int_ptr_assign(self, *args)

    def value(self):
        """value(self) -> int"""
        return _pyautolib.int_ptr_value(self)

    def cast(self):
        """cast(self) -> int"""
        return _pyautolib.int_ptr_cast(self)

    def frompointer(*args):
        """frompointer(int t) -> int_ptr"""
        return _pyautolib.int_ptr_frompointer(*args)

    if _newclass:frompointer = staticmethod(frompointer)
    __swig_getmethods__["frompointer"] = lambda x: frompointer
int_ptr_swigregister = _pyautolib.int_ptr_swigregister
int_ptr_swigregister(int_ptr)

def int_ptr_frompointer(*args):
  """int_ptr_frompointer(int t) -> int_ptr"""
  return _pyautolib.int_ptr_frompointer(*args)

class uint32_ptr(_object):
    """Proxy of C++ uint32_ptr class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, uint32_ptr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, uint32_ptr, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> uint32_ptr"""
        this = _pyautolib.new_uint32_ptr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pyautolib.delete_uint32_ptr
    __del__ = lambda self : None;
    def assign(self, *args):
        """assign(self, uint32 value)"""
        return _pyautolib.uint32_ptr_assign(self, *args)

    def value(self):
        """value(self) -> uint32"""
        return _pyautolib.uint32_ptr_value(self)

    def cast(self):
        """cast(self) -> uint32"""
        return _pyautolib.uint32_ptr_cast(self)

    def frompointer(*args):
        """frompointer(uint32 t) -> uint32_ptr"""
        return _pyautolib.uint32_ptr_frompointer(*args)

    if _newclass:frompointer = staticmethod(frompointer)
    __swig_getmethods__["frompointer"] = lambda x: frompointer
uint32_ptr_swigregister = _pyautolib.uint32_ptr_swigregister
uint32_ptr_swigregister(uint32_ptr)

def uint32_ptr_frompointer(*args):
  """uint32_ptr_frompointer(uint32 t) -> uint32_ptr"""
  return _pyautolib.uint32_ptr_frompointer(*args)



